`timescale 1ns/1ps
`default_nettype none
// Optional asynchronous management publication wrapper. The synchronous
// managed Endpoint remains the only CSR and transaction owner in i_fabric_clk.
module ualink_endpoint_transaction_station_managed_async_top #(
 parameter integer C_NUM_STATIONS=2,parameter integer C_FLAT_STATIONS=(C_NUM_STATIONS<1)?1:C_NUM_STATIONS,
 parameter integer WIDTH=8,parameter integer HEADER_DEPTH=2,parameter integer BANK_DEPTH=3,parameter integer RX_DEPTH=40,
 parameter integer ORIGINATOR_CAPACITY=4,parameter integer COMPLETER_CAPACITY=4,parameter integer REPLAY_DEPTH=4,parameter integer EXPLICIT_PACKET_BOUNDARY_ENABLE=0,parameter integer INTERNAL_PACKET_BOUNDARY_ENABLE=1,
 parameter integer REPLAY_ADDR_WIDTH=(REPLAY_DEPTH<=2)?1:(REPLAY_DEPTH<=4)?2:(REPLAY_DEPTH<=8)?3:(REPLAY_DEPTH<=16)?4:(REPLAY_DEPTH<=32)?5:(REPLAY_DEPTH<=64)?6:(REPLAY_DEPTH<=128)?7:8
)(
 input wire i_mgmt_clk,input wire i_mgmt_rstn,input wire i_fabric_clk,input wire i_fabric_rstn,input wire i_enable,input wire i_csr_req_valid,output wire o_csr_req_ready,input wire i_csr_req_write,input wire[15:0] i_csr_req_addr,input wire[31:0] i_csr_req_wdata,output wire o_csr_rsp_valid,input wire i_csr_rsp_ready,output wire[31:0] o_csr_rsp_rdata,output wire o_csr_rsp_error,output wire o_csr_rsp_unsupported,
 input wire[C_FLAT_STATIONS*4-1:0] i_lane_up,output wire[C_FLAT_STATIONS*2-1:0] o_requested_mode,output wire[C_FLAT_STATIONS-1:0] o_mode_commit,output wire[C_FLAT_STATIONS*4-1:0] o_port_link_reset,
 input wire[C_FLAT_STATIONS*4-1:0] i_start,input wire[C_FLAT_STATIONS*4-1:0] i_shared,input wire[C_FLAT_STATIONS*80*WIDTH-1:0] i_capacities,input wire[C_FLAT_STATIONS*4-1:0] i_native_sop,input wire[C_FLAT_STATIONS*4-1:0] i_native_eop,output wire[C_FLAT_STATIONS*4-1:0] o_native_boundary_take,
 output wire[C_FLAT_STATIONS-1:0] o_mode_commit_accept,output wire[C_FLAT_STATIONS-1:0] o_mode_error,output wire[C_FLAT_STATIONS*2-1:0] o_active_mode,output wire[C_FLAT_STATIONS*4-1:0] o_active_mask,output wire[C_FLAT_STATIONS*4-1:0] o_port_slot_enable,output wire[C_FLAT_STATIONS*2-1:0] o_slot_port,output wire[C_FLAT_STATIONS-1:0] o_slot_error,
 input wire[C_FLAT_STATIONS*4-1:0] i_rate_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rate_ready,input wire[C_FLAT_STATIONS*64-1:0] i_rate_code,output wire[C_FLAT_STATIONS*4-1:0] o_rate_accept,output wire[C_FLAT_STATIONS*4-1:0] o_rate_error,output wire[C_FLAT_STATIONS*4-1:0] o_rate_configured,output wire[C_FLAT_STATIONS*64-1:0] o_active_rate_code,input wire[C_FLAT_STATIONS*4-1:0] i_tx_budget_available,
 input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rx_frame_ready,input wire[C_FLAT_STATIONS*2048-1:0] i_rx_frame_data,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_sop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_eop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_fec_complete,input wire[C_FLAT_STATIONS*4-1:0] i_rx_crc_ok,
 output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_valid,input wire[C_FLAT_STATIONS*4-1:0] i_tx_control_ready,output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_replay_request,output wire[C_FLAT_STATIONS*36-1:0] o_tx_control_target,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_valid,input wire[C_FLAT_STATIONS*4-1:0] i_crc_input_ready,output wire[C_FLAT_STATIONS*2048-1:0] o_crc_input_data,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_sop,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_eop,output wire[C_FLAT_STATIONS*36-1:0] o_crc_input_sequence,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_replay,output wire[C_FLAT_STATIONS*4-1:0] o_crc_required,output wire[C_FLAT_STATIONS*4-1:0] o_physical_valid,output wire[C_FLAT_STATIONS*32-1:0] o_tx_resident_count,
 input wire[C_FLAT_STATIONS*10-1:0] i_local_id,input wire[C_FLAT_STATIONS-1:0] i_request_valid,output wire[C_FLAT_STATIONS-1:0] o_request_ready,input wire[C_FLAT_STATIONS*2-1:0] i_request_port,input wire[C_FLAT_STATIONS*11-1:0] i_request_tag,input wire[C_FLAT_STATIONS*57-1:0] i_request_address,input wire[C_FLAT_STATIONS*10-1:0] i_request_dst,input wire[C_FLAT_STATIONS*6-1:0] i_request_length,input wire[C_FLAT_STATIONS*8-1:0] i_request_attr,
 output wire[C_FLAT_STATIONS-1:0] o_complete_valid,input wire[C_FLAT_STATIONS-1:0] i_complete_ready,output wire[C_FLAT_STATIONS*2-1:0] o_complete_port,output wire[C_FLAT_STATIONS*11-1:0] o_complete_tag,output wire[C_FLAT_STATIONS*4-1:0] o_complete_status,output wire[C_FLAT_STATIONS*512-1:0] o_complete_data,output wire[C_FLAT_STATIONS-1:0] o_complete_data_valid,
 output wire[C_FLAT_STATIONS-1:0] o_mem_valid,input wire[C_FLAT_STATIONS-1:0] i_mem_ready,output wire[C_FLAT_STATIONS*2-1:0] o_mem_slot,output wire[C_FLAT_STATIONS*57-1:0] o_mem_address,output wire[C_FLAT_STATIONS*6-1:0] o_mem_length,output wire[C_FLAT_STATIONS*8-1:0] o_mem_attr,output wire[C_FLAT_STATIONS*2-1:0] o_mem_asi,output wire[C_FLAT_STATIONS*8-1:0] o_mem_metadata,input wire[C_FLAT_STATIONS-1:0] i_mem_result_valid,output wire[C_FLAT_STATIONS-1:0] o_mem_result_ready,input wire[C_FLAT_STATIONS*2-1:0] i_mem_result_slot,input wire[C_FLAT_STATIONS*512-1:0] i_mem_result_data,input wire[C_FLAT_STATIONS*4-1:0] i_mem_result_status,
 output wire[C_FLAT_STATIONS*4-1:0] o_start_ready,output wire[C_FLAT_STATIONS*4-1:0] o_start_taken,output wire[C_FLAT_STATIONS*4-1:0] o_local_done,output wire[C_FLAT_STATIONS*4-1:0] o_peer_done,output wire[C_FLAT_STATIONS*4-1:0] o_port_error,output wire[C_FLAT_STATIONS*4-1:0] o_remote_request_reject_pulse,output wire[C_FLAT_STATIONS*4-1:0] o_remote_request_reject_sticky,output wire[C_FLAT_STATIONS-1:0] o_transaction_error,output wire[C_FLAT_STATIONS-1:0] o_scheduled_error,output wire[C_FLAT_STATIONS-1:0] o_station_busy,output wire[C_FLAT_STATIONS-1:0] o_station_quiescent,output wire[C_FLAT_STATIONS-1:0] o_station_error,output wire o_busy,output wire o_quiescent,output wire o_csr_error_sticky,output wire o_security_unsupported,output wire o_config_error,output wire o_error
);
 wire fabric_csr_req_valid,fabric_csr_req_ready,fabric_csr_req_write;
 wire[15:0] fabric_csr_req_addr;wire[31:0] fabric_csr_req_wdata;
 wire fabric_csr_rsp_valid,fabric_csr_rsp_ready,fabric_csr_rsp_error,fabric_csr_rsp_unsupported;
 wire[31:0] fabric_csr_rsp_rdata;
 endpoint_management_cdc_bridge u_management_cdc(
  .i_mgmt_clk(i_mgmt_clk),.i_mgmt_rstn(i_mgmt_rstn),.i_mgmt_req_valid(i_csr_req_valid),.o_mgmt_req_ready(o_csr_req_ready),
  .i_mgmt_req_write(i_csr_req_write),.i_mgmt_req_addr(i_csr_req_addr),.i_mgmt_req_wdata(i_csr_req_wdata),
  .o_mgmt_rsp_valid(o_csr_rsp_valid),.i_mgmt_rsp_ready(i_csr_rsp_ready),.o_mgmt_rsp_rdata(o_csr_rsp_rdata),
  .o_mgmt_rsp_error(o_csr_rsp_error),.o_mgmt_rsp_unsupported(o_csr_rsp_unsupported),
  .i_fabric_clk(i_fabric_clk),.i_fabric_rstn(i_fabric_rstn),.o_fabric_req_valid(fabric_csr_req_valid),
  .i_fabric_req_ready(fabric_csr_req_ready),.o_fabric_req_write(fabric_csr_req_write),.o_fabric_req_addr(fabric_csr_req_addr),
  .o_fabric_req_wdata(fabric_csr_req_wdata),.i_fabric_rsp_valid(fabric_csr_rsp_valid),.o_fabric_rsp_ready(fabric_csr_rsp_ready),
  .i_fabric_rsp_rdata(fabric_csr_rsp_rdata),.i_fabric_rsp_error(fabric_csr_rsp_error),.i_fabric_rsp_unsupported(fabric_csr_rsp_unsupported));
 ualink_endpoint_transaction_station_managed_top #(
  .C_NUM_STATIONS(C_NUM_STATIONS),
  .C_FLAT_STATIONS(C_FLAT_STATIONS),
  .WIDTH(WIDTH),
  .HEADER_DEPTH(HEADER_DEPTH),
  .BANK_DEPTH(BANK_DEPTH),
  .RX_DEPTH(RX_DEPTH),
  .ORIGINATOR_CAPACITY(ORIGINATOR_CAPACITY),
  .COMPLETER_CAPACITY(COMPLETER_CAPACITY),
  .REPLAY_DEPTH(REPLAY_DEPTH),
  .EXPLICIT_PACKET_BOUNDARY_ENABLE(EXPLICIT_PACKET_BOUNDARY_ENABLE),.INTERNAL_PACKET_BOUNDARY_ENABLE(INTERNAL_PACKET_BOUNDARY_ENABLE),
  .REPLAY_ADDR_WIDTH(REPLAY_ADDR_WIDTH)
 )u_managed(
  .i_clk(i_fabric_clk),
  .i_rstn(i_fabric_rstn),
  .i_enable(i_enable),
  .i_csr_req_valid(fabric_csr_req_valid),
  .o_csr_req_ready(fabric_csr_req_ready),
  .i_csr_req_write(fabric_csr_req_write),
  .i_csr_req_addr(fabric_csr_req_addr),
  .i_csr_req_wdata(fabric_csr_req_wdata),
  .o_csr_rsp_valid(fabric_csr_rsp_valid),
  .i_csr_rsp_ready(fabric_csr_rsp_ready),
  .o_csr_rsp_rdata(fabric_csr_rsp_rdata),
  .o_csr_rsp_error(fabric_csr_rsp_error),
  .o_csr_rsp_unsupported(fabric_csr_rsp_unsupported),
  .i_lane_up(i_lane_up),
  .o_requested_mode(o_requested_mode),
  .o_mode_commit(o_mode_commit),
  .o_port_link_reset(o_port_link_reset),
  .i_start(i_start),
  .i_shared(i_shared),
  .i_capacities(i_capacities),
  .i_native_sop(i_native_sop),
  .i_native_eop(i_native_eop),
  .o_native_boundary_take(o_native_boundary_take),
  .o_mode_commit_accept(o_mode_commit_accept),
  .o_mode_error(o_mode_error),
  .o_active_mode(o_active_mode),
  .o_active_mask(o_active_mask),
  .o_port_slot_enable(o_port_slot_enable),
  .o_slot_port(o_slot_port),
  .o_slot_error(o_slot_error),
  .i_rate_valid(i_rate_valid),
  .o_rate_ready(o_rate_ready),
  .i_rate_code(i_rate_code),
  .o_rate_accept(o_rate_accept),
  .o_rate_error(o_rate_error),
  .o_rate_configured(o_rate_configured),
  .o_active_rate_code(o_active_rate_code),
  .i_tx_budget_available(i_tx_budget_available),
  .i_rx_frame_valid(i_rx_frame_valid),
  .o_rx_frame_ready(o_rx_frame_ready),
  .i_rx_frame_data(i_rx_frame_data),
  .i_rx_frame_sop(i_rx_frame_sop),
  .i_rx_frame_eop(i_rx_frame_eop),
  .i_rx_fec_complete(i_rx_fec_complete),
  .i_rx_crc_ok(i_rx_crc_ok),
  .o_tx_control_valid(o_tx_control_valid),
  .i_tx_control_ready(i_tx_control_ready),
  .o_tx_control_replay_request(o_tx_control_replay_request),
  .o_tx_control_target(o_tx_control_target),
  .o_crc_input_valid(o_crc_input_valid),
  .i_crc_input_ready(i_crc_input_ready),
  .o_crc_input_data(o_crc_input_data),
  .o_crc_input_sop(o_crc_input_sop),
  .o_crc_input_eop(o_crc_input_eop),
  .o_crc_input_sequence(o_crc_input_sequence),
  .o_crc_input_replay(o_crc_input_replay),
  .o_crc_required(o_crc_required),
  .o_physical_valid(o_physical_valid),
  .o_tx_resident_count(o_tx_resident_count),
  .i_local_id(i_local_id),
  .i_request_valid(i_request_valid),
  .o_request_ready(o_request_ready),
  .i_request_port(i_request_port),
  .i_request_tag(i_request_tag),
  .i_request_address(i_request_address),
  .i_request_dst(i_request_dst),
  .i_request_length(i_request_length),
  .i_request_attr(i_request_attr),
  .o_complete_valid(o_complete_valid),
  .i_complete_ready(i_complete_ready),
  .o_complete_port(o_complete_port),
  .o_complete_tag(o_complete_tag),
  .o_complete_status(o_complete_status),
  .o_complete_data(o_complete_data),
  .o_complete_data_valid(o_complete_data_valid),
  .o_mem_valid(o_mem_valid),
  .i_mem_ready(i_mem_ready),
  .o_mem_slot(o_mem_slot),
  .o_mem_address(o_mem_address),
  .o_mem_length(o_mem_length),
  .o_mem_attr(o_mem_attr),
  .o_mem_asi(o_mem_asi),
  .o_mem_metadata(o_mem_metadata),
  .i_mem_result_valid(i_mem_result_valid),
  .o_mem_result_ready(o_mem_result_ready),
  .i_mem_result_slot(i_mem_result_slot),
  .i_mem_result_data(i_mem_result_data),
  .i_mem_result_status(i_mem_result_status),
  .o_start_ready(o_start_ready),
  .o_start_taken(o_start_taken),
  .o_local_done(o_local_done),
  .o_peer_done(o_peer_done),
  .o_port_error(o_port_error),
  .o_remote_request_reject_pulse(o_remote_request_reject_pulse),
  .o_remote_request_reject_sticky(o_remote_request_reject_sticky),
  .o_transaction_error(o_transaction_error),
  .o_scheduled_error(o_scheduled_error),
  .o_station_busy(o_station_busy),
  .o_station_quiescent(o_station_quiescent),
  .o_station_error(o_station_error),
  .o_busy(o_busy),
  .o_quiescent(o_quiescent),
  .o_csr_error_sticky(o_csr_error_sticky),
  .o_security_unsupported(o_security_unsupported),
  .o_config_error(o_config_error),
  .o_error(o_error)
 );
endmodule
`default_nettype wire
