`timescale 1ns/1ps
`default_nettype none
// 参数化production Endpoint transaction Station阵列。每个Station实例化一个完整
// transaction->唯一四tl_port owner->pacing/calendar->四独立DL replay context组合器。
// 阵列仅展平接口并聚合诊断；Station之间不共享credit、sequence、replay或日历状态。
// A19 CRC物理映射仍未冻结，因此各Station继承physical_valid恒零的失败关闭边界。
module ualink_endpoint_transaction_station_array #(
 parameter integer C_NUM_STATIONS=2,parameter integer C_FLAT_STATIONS=(C_NUM_STATIONS<1)?1:C_NUM_STATIONS,
 parameter integer WIDTH=8,parameter integer HEADER_DEPTH=2,parameter integer BANK_DEPTH=3,parameter integer RX_DEPTH=40,
 parameter integer HEADER_COUNT_WIDTH=(HEADER_DEPTH<2)?1:(HEADER_DEPTH<4)?2:3,parameter integer DATA_COUNT_WIDTH=(BANK_DEPTH<2)?1:(BANK_DEPTH<4)?2:3,
 parameter integer RX_COUNT_WIDTH=(RX_DEPTH<2)?1:(RX_DEPTH<4)?2:(RX_DEPTH<8)?3:(RX_DEPTH<16)?4:(RX_DEPTH<32)?5:(RX_DEPTH<64)?6:7,
 parameter integer ORIGINATOR_CAPACITY=4,parameter integer COMPLETER_CAPACITY=4,parameter integer MESSAGE_ENABLE=0,parameter integer MESSAGE_TOKEN_WIDTH=16,parameter integer NORMAL_WRITE_ENABLE=0,parameter integer FULL_READ_ENABLE=0,parameter integer ATOMIC_ENABLE=0,parameter integer ATOMIC_TX_CLOSE_ENABLE=0,parameter integer ATOMIC_TOKEN_WIDTH=16,parameter integer ORDINARY_ORDERING_ENABLE=0,parameter integer REPLAY_DEPTH=4,parameter integer DYNAMIC_MODE_ENABLE=0,parameter integer EXPLICIT_PACKET_BOUNDARY_ENABLE=0,parameter integer INTERNAL_PACKET_BOUNDARY_ENABLE=0,
 parameter integer REPLAY_ADDR_WIDTH=(REPLAY_DEPTH<=2)?1:(REPLAY_DEPTH<=4)?2:(REPLAY_DEPTH<=8)?3:(REPLAY_DEPTH<=16)?4:(REPLAY_DEPTH<=32)?5:(REPLAY_DEPTH<=64)?6:(REPLAY_DEPTH<=128)?7:8,
 parameter [3:0] ACTIVE_PORT_MASK=4'b0101
)(
 input wire i_clk,input wire i_rstn,input wire i_enable,input wire[C_FLAT_STATIONS-1:0] i_remote_request_admission_enable,input wire[C_FLAT_STATIONS-1:0] i_ras_rx_cleanup,
 input wire[C_FLAT_STATIONS*4-1:0] i_port_link_reset,input wire[C_FLAT_STATIONS*4-1:0] i_start,input wire[C_FLAT_STATIONS*4-1:0] i_shared,input wire[C_FLAT_STATIONS*80*WIDTH-1:0] i_capacities,input wire[C_FLAT_STATIONS*4-1:0] i_native_sop,input wire[C_FLAT_STATIONS*4-1:0] i_native_eop,output wire[C_FLAT_STATIONS*4-1:0] o_native_boundary_take,
 input wire[C_FLAT_STATIONS*2-1:0] i_requested_mode,input wire[C_FLAT_STATIONS-1:0] i_mode_commit,input wire[C_FLAT_STATIONS*4-1:0] i_lane_up,output wire[C_FLAT_STATIONS-1:0] o_mode_commit_accept,output wire[C_FLAT_STATIONS-1:0] o_mode_error,
 output wire[C_FLAT_STATIONS*2-1:0] o_active_mode,output wire[C_FLAT_STATIONS*4-1:0] o_active_mask,output wire[C_FLAT_STATIONS*4-1:0] o_port_slot_enable,output wire[C_FLAT_STATIONS*2-1:0] o_slot_port,output wire[C_FLAT_STATIONS-1:0] o_slot_error,
 input wire[C_FLAT_STATIONS*4-1:0] i_rate_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rate_ready,input wire[C_FLAT_STATIONS*64-1:0] i_rate_code,
 output wire[C_FLAT_STATIONS*4-1:0] o_rate_accept,output wire[C_FLAT_STATIONS*4-1:0] o_rate_error,output wire[C_FLAT_STATIONS*4-1:0] o_rate_configured,output wire[C_FLAT_STATIONS*64-1:0] o_active_rate_code,input wire[C_FLAT_STATIONS*4-1:0] i_tx_budget_available,
 input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rx_frame_ready,input wire[C_FLAT_STATIONS*2048-1:0] i_rx_frame_data,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_sop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_eop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_fec_complete,input wire[C_FLAT_STATIONS*4-1:0] i_rx_crc_ok,
 output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_valid,input wire[C_FLAT_STATIONS*4-1:0] i_tx_control_ready,output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_replay_request,output wire[C_FLAT_STATIONS*36-1:0] o_tx_control_target,
 output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_valid,input wire[C_FLAT_STATIONS*4-1:0] i_crc_input_ready,output wire[C_FLAT_STATIONS*2048-1:0] o_crc_input_data,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_sop,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_eop,output wire[C_FLAT_STATIONS*36-1:0] o_crc_input_sequence,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_replay,output wire[C_FLAT_STATIONS*4-1:0] o_crc_required,output wire[C_FLAT_STATIONS*4-1:0] o_physical_valid,output wire[C_FLAT_STATIONS*32-1:0] o_tx_resident_count,
 input wire[C_FLAT_STATIONS*10-1:0] i_local_id,input wire[C_FLAT_STATIONS-1:0] i_request_valid,output wire[C_FLAT_STATIONS-1:0] o_request_ready,input wire[C_FLAT_STATIONS*2-1:0] i_request_port,input wire[C_FLAT_STATIONS*11-1:0] i_request_tag,input wire[C_FLAT_STATIONS*57-1:0] i_request_address,input wire[C_FLAT_STATIONS*10-1:0] i_request_dst,input wire[C_FLAT_STATIONS*6-1:0] i_request_length,input wire[C_FLAT_STATIONS*8-1:0] i_request_attr,
 input wire[C_FLAT_STATIONS-1:0] i_request_is_write,input wire[C_FLAT_STATIONS-1:0] i_request_full,input wire[C_FLAT_STATIONS*2-1:0] i_request_asi,input wire[C_FLAT_STATIONS*8-1:0] i_request_metadata,input wire[C_FLAT_STATIONS*2048-1:0] i_request_data,input wire[C_FLAT_STATIONS*256-1:0] i_request_be,
 input wire[C_FLAT_STATIONS*4-1:0] i_order_profile_valid,input wire[C_FLAT_STATIONS*8-1:0] i_order_mode,input wire[C_FLAT_STATIONS*32-1:0] i_order_epoch,input wire[C_FLAT_STATIONS*4-1:0] i_order_affinity_valid,input wire[C_FLAT_STATIONS*8-1:0] i_order_actual_vc,output wire[C_FLAT_STATIONS*4-1:0] o_order_busy,output wire[C_FLAT_STATIONS*4-1:0] o_order_quiescent,output wire[C_FLAT_STATIONS*4-1:0] o_order_error,
 output wire[C_FLAT_STATIONS-1:0] o_complete_valid,input wire[C_FLAT_STATIONS-1:0] i_complete_ready,output wire[C_FLAT_STATIONS*2-1:0] o_complete_port,output wire[C_FLAT_STATIONS*11-1:0] o_complete_tag,output wire[C_FLAT_STATIONS*4-1:0] o_complete_status,output wire[C_FLAT_STATIONS*512-1:0] o_complete_data,output wire[C_FLAT_STATIONS-1:0] o_complete_data_valid,
 output wire[C_FLAT_STATIONS-1:0] o_complete_is_write,output wire[C_FLAT_STATIONS*2048-1:0] o_complete_data_full,output wire[C_FLAT_STATIONS*256-1:0] o_complete_mask,
 output wire[C_FLAT_STATIONS-1:0] o_mem_valid,input wire[C_FLAT_STATIONS-1:0] i_mem_ready,output wire[C_FLAT_STATIONS*2-1:0] o_mem_slot,output wire[C_FLAT_STATIONS*57-1:0] o_mem_address,output wire[C_FLAT_STATIONS*6-1:0] o_mem_length,output wire[C_FLAT_STATIONS*8-1:0] o_mem_attr,output wire[C_FLAT_STATIONS*2-1:0] o_mem_asi,output wire[C_FLAT_STATIONS*8-1:0] o_mem_metadata,
 input wire[C_FLAT_STATIONS-1:0] i_mem_result_valid,output wire[C_FLAT_STATIONS-1:0] o_mem_result_ready,input wire[C_FLAT_STATIONS*2-1:0] i_mem_result_slot,input wire[C_FLAT_STATIONS*512-1:0] i_mem_result_data,input wire[C_FLAT_STATIONS*4-1:0] i_mem_result_status,
 input wire[C_FLAT_STATIONS*2048-1:0] i_mem_result_data_full,output wire[C_FLAT_STATIONS*256-1:0] o_mem_be,
 output wire[C_FLAT_STATIONS-1:0] o_write_mem_valid,input wire[C_FLAT_STATIONS-1:0] i_write_mem_ready,output wire[C_FLAT_STATIONS*2-1:0] o_write_mem_slot,output wire[C_FLAT_STATIONS*57-1:0] o_write_mem_address,output wire[C_FLAT_STATIONS*6-1:0] o_write_mem_length,output wire[C_FLAT_STATIONS*8-1:0] o_write_mem_attr,output wire[C_FLAT_STATIONS*2-1:0] o_write_mem_asi,output wire[C_FLAT_STATIONS*8-1:0] o_write_mem_metadata,output wire[C_FLAT_STATIONS*2048-1:0] o_write_mem_data,output wire[C_FLAT_STATIONS*256-1:0] o_write_mem_be,
 input wire[C_FLAT_STATIONS-1:0] i_write_mem_result_valid,output wire[C_FLAT_STATIONS-1:0] o_write_mem_result_ready,input wire[C_FLAT_STATIONS*2-1:0] i_write_mem_result_slot,input wire[C_FLAT_STATIONS*4-1:0] i_write_mem_result_status,output wire[C_FLAT_STATIONS*8-1:0] o_write_completer_count,
 input wire[C_FLAT_STATIONS*32-1:0] i_atomic_profile_valid,input wire[C_FLAT_STATIONS*32-1:0] i_atomic_two_operand,input wire[C_FLAT_STATIONS-1:0] i_atomic_order_profile_valid,input wire[C_FLAT_STATIONS*2-1:0] i_atomic_order_mode,input wire[C_FLAT_STATIONS*8-1:0] i_atomic_order_epoch,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_valid,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_backend_ready,output wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] o_atomic_backend_token,output wire[C_FLAT_STATIONS*512-1:0] o_atomic_backend_header,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_backend_port,output wire[C_FLAT_STATIONS*2048-1:0] o_atomic_backend_operands,output wire[C_FLAT_STATIONS*1024-1:0] o_atomic_backend_byte_enable,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_atomic_return,output wire[C_FLAT_STATIONS*20-1:0] o_atomic_backend_op_type,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_backend_op_size,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_backend_result_valid,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_result_ready,input wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] i_atomic_backend_result_token,input wire[C_FLAT_STATIONS*16-1:0] i_atomic_backend_result_status,input wire[C_FLAT_STATIONS*2048-1:0] i_atomic_backend_result_data,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_valid,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_response_ready,output wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] o_atomic_response_token,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_atomic_return,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_response_port,output wire[C_FLAT_STATIONS*44-1:0] o_atomic_response_tag,output wire[C_FLAT_STATIONS*40-1:0] o_atomic_response_src,output wire[C_FLAT_STATIONS*40-1:0] o_atomic_response_dst,output wire[C_FLAT_STATIONS*16-1:0] o_atomic_response_status,output wire[C_FLAT_STATIONS*2048-1:0] o_atomic_response_data,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_data_valid,
 output wire[C_FLAT_STATIONS-1:0] o_message_backend_valid,input wire[C_FLAT_STATIONS-1:0] i_message_backend_ready,output wire[C_FLAT_STATIONS*MESSAGE_TOKEN_WIDTH-1:0] o_message_backend_token,output wire[C_FLAT_STATIONS*128-1:0] o_message_backend_header,output wire[C_FLAT_STATIONS*2-1:0] o_message_backend_port,output wire[C_FLAT_STATIONS*2048-1:0] o_message_backend_data,output wire[C_FLAT_STATIONS*256-1:0] o_message_backend_be,
 input wire[C_FLAT_STATIONS-1:0] i_message_result_valid,output wire[C_FLAT_STATIONS-1:0] o_message_result_ready,input wire[C_FLAT_STATIONS*MESSAGE_TOKEN_WIDTH-1:0] i_message_result_token,input wire[C_FLAT_STATIONS-1:0] i_message_result_is_read,input wire[C_FLAT_STATIONS*2-1:0] i_message_result_num_beats,input wire[C_FLAT_STATIONS*4-1:0] i_message_result_status,input wire[C_FLAT_STATIONS*2048-1:0] i_message_result_data,input wire[C_FLAT_STATIONS*4-1:0] i_message_result_poison,output wire[C_FLAT_STATIONS-1:0] o_message_busy,output wire[C_FLAT_STATIONS*8-1:0] o_message_reason,
 output wire[C_FLAT_STATIONS*4-1:0] o_start_ready,output wire[C_FLAT_STATIONS*4-1:0] o_start_taken,output wire[C_FLAT_STATIONS*4-1:0] o_local_done,output wire[C_FLAT_STATIONS*4-1:0] o_peer_done,output wire[C_FLAT_STATIONS*4-1:0] o_port_error,
 output wire[C_FLAT_STATIONS-1:0] o_transaction_error,output wire[C_FLAT_STATIONS-1:0] o_scheduled_error,output wire[C_FLAT_STATIONS*4-1:0] o_remote_request_reject_pulse,output wire[C_FLAT_STATIONS-1:0] o_station_busy,output wire[C_FLAT_STATIONS-1:0] o_station_quiescent,output wire[C_FLAT_STATIONS-1:0] o_station_error,output wire[C_FLAT_STATIONS*3-1:0] o_ras_owner_ready,output wire[C_FLAT_STATIONS*3-1:0] o_ras_missing_owners,output wire o_config_error,output wire o_error
);
 localparam CONFIG_LEGAL=(C_NUM_STATIONS>=1)&&(C_NUM_STATIONS<=256)&&(C_FLAT_STATIONS==C_NUM_STATIONS);
 assign o_config_error=!CONFIG_LEGAL;
 assign o_error=o_config_error||(|o_station_error);
 genvar s;generate if(CONFIG_LEGAL)begin:gen_legal for(s=0;s<32'd256;s=s+32'd1)begin:gen_station if(s<C_NUM_STATIONS)begin:gen_present
  endpoint_station_transaction_dl_composer #(.WIDTH(WIDTH),.HEADER_DEPTH(HEADER_DEPTH),.BANK_DEPTH(BANK_DEPTH),.RX_DEPTH(RX_DEPTH),.HEADER_COUNT_WIDTH(HEADER_COUNT_WIDTH),.DATA_COUNT_WIDTH(DATA_COUNT_WIDTH),.RX_COUNT_WIDTH(RX_COUNT_WIDTH),.ORIGINATOR_CAPACITY(ORIGINATOR_CAPACITY),.COMPLETER_CAPACITY(COMPLETER_CAPACITY),.MESSAGE_ENABLE(MESSAGE_ENABLE),.MESSAGE_TOKEN_WIDTH(MESSAGE_TOKEN_WIDTH),.NORMAL_WRITE_ENABLE(NORMAL_WRITE_ENABLE),.FULL_READ_ENABLE(FULL_READ_ENABLE),.ATOMIC_ENABLE(ATOMIC_ENABLE),.ATOMIC_TX_CLOSE_ENABLE(ATOMIC_TX_CLOSE_ENABLE),.ATOMIC_TOKEN_WIDTH(ATOMIC_TOKEN_WIDTH),.ORDINARY_ORDERING_ENABLE(ORDINARY_ORDERING_ENABLE),.REPLAY_DEPTH(REPLAY_DEPTH),.REPLAY_ADDR_WIDTH(REPLAY_ADDR_WIDTH),.DYNAMIC_MODE_ENABLE(DYNAMIC_MODE_ENABLE),.EXPLICIT_PACKET_BOUNDARY_ENABLE(EXPLICIT_PACKET_BOUNDARY_ENABLE),.INTERNAL_PACKET_BOUNDARY_ENABLE(INTERNAL_PACKET_BOUNDARY_ENABLE),.ACTIVE_PORT_MASK(ACTIVE_PORT_MASK)) u_station(
   .i_clk(i_clk),.i_rstn(i_rstn),.i_enable(i_enable),.i_remote_request_admission_enable(i_remote_request_admission_enable[s]),.i_ras_rx_cleanup(i_ras_rx_cleanup[s]),.i_port_link_reset(i_port_link_reset[s*4+:4]),.i_start(i_start[s*4+:4]),.i_shared(i_shared[s*4+:4]),.i_capacities(i_capacities[s*80*WIDTH+:80*WIDTH]),.i_native_sop(i_native_sop[s*4+:4]),.i_native_eop(i_native_eop[s*4+:4]),.o_native_boundary_take(o_native_boundary_take[s*4+:4]),
   .i_requested_mode(i_requested_mode[s*2+:2]),.i_mode_commit(i_mode_commit[s]),.i_lane_up(i_lane_up[s*4+:4]),.o_mode_commit_accept(o_mode_commit_accept[s]),.o_mode_error(o_mode_error[s]),.o_active_mode(o_active_mode[s*2+:2]),.o_active_mask(o_active_mask[s*4+:4]),.o_port_slot_enable(o_port_slot_enable[s*4+:4]),.o_slot_port(o_slot_port[s*2+:2]),.o_slot_error(o_slot_error[s]),
   .i_rate_valid(i_rate_valid[s*4+:4]),.o_rate_ready(o_rate_ready[s*4+:4]),.i_rate_code(i_rate_code[s*64+:64]),.o_rate_accept(o_rate_accept[s*4+:4]),.o_rate_error(o_rate_error[s*4+:4]),.o_rate_configured(o_rate_configured[s*4+:4]),.o_active_rate_code(o_active_rate_code[s*64+:64]),.i_tx_budget_available(i_tx_budget_available[s*4+:4]),
   .i_rx_frame_valid(i_rx_frame_valid[s*4+:4]),.o_rx_frame_ready(o_rx_frame_ready[s*4+:4]),.i_rx_frame_data(i_rx_frame_data[s*2048+:2048]),.i_rx_frame_sop(i_rx_frame_sop[s*4+:4]),.i_rx_frame_eop(i_rx_frame_eop[s*4+:4]),.i_rx_fec_complete(i_rx_fec_complete[s*4+:4]),.i_rx_crc_ok(i_rx_crc_ok[s*4+:4]),
   .o_tx_control_valid(o_tx_control_valid[s*4+:4]),.i_tx_control_ready(i_tx_control_ready[s*4+:4]),.o_tx_control_replay_request(o_tx_control_replay_request[s*4+:4]),.o_tx_control_target(o_tx_control_target[s*36+:36]),.o_crc_input_valid(o_crc_input_valid[s*4+:4]),.i_crc_input_ready(i_crc_input_ready[s*4+:4]),.o_crc_input_data(o_crc_input_data[s*2048+:2048]),.o_crc_input_sop(o_crc_input_sop[s*4+:4]),.o_crc_input_eop(o_crc_input_eop[s*4+:4]),.o_crc_input_sequence(o_crc_input_sequence[s*36+:36]),.o_crc_input_replay(o_crc_input_replay[s*4+:4]),.o_crc_required(o_crc_required[s*4+:4]),.o_physical_valid(o_physical_valid[s*4+:4]),.o_tx_resident_count(o_tx_resident_count[s*32+:32]),
   .i_local_id(i_local_id[s*10+:10]),.i_request_valid(i_request_valid[s]),.o_request_ready(o_request_ready[s]),.i_request_port(i_request_port[s*2+:2]),.i_request_tag(i_request_tag[s*11+:11]),.i_request_address(i_request_address[s*57+:57]),.i_request_dst(i_request_dst[s*10+:10]),.i_request_length(i_request_length[s*6+:6]),.i_request_attr(i_request_attr[s*8+:8]),
   .i_request_is_write(i_request_is_write[s]),.i_request_full(i_request_full[s]),.i_request_asi(i_request_asi[s*2+:2]),.i_request_metadata(i_request_metadata[s*8+:8]),.i_request_data(i_request_data[s*2048+:2048]),.i_request_be(i_request_be[s*256+:256]),
   .i_order_profile_valid(i_order_profile_valid[s*4+:4]),.i_order_mode(i_order_mode[s*8+:8]),.i_order_epoch(i_order_epoch[s*32+:32]),.i_order_affinity_valid(i_order_affinity_valid[s*4+:4]),.i_order_actual_vc(i_order_actual_vc[s*8+:8]),.o_order_busy(o_order_busy[s*4+:4]),.o_order_quiescent(o_order_quiescent[s*4+:4]),.o_order_error(o_order_error[s*4+:4]),
   .o_complete_valid(o_complete_valid[s]),.i_complete_ready(i_complete_ready[s]),.o_complete_port(o_complete_port[s*2+:2]),.o_complete_tag(o_complete_tag[s*11+:11]),.o_complete_status(o_complete_status[s*4+:4]),.o_complete_data(o_complete_data[s*512+:512]),.o_complete_data_valid(o_complete_data_valid[s]),.o_complete_is_write(o_complete_is_write[s]),.o_complete_data_full(o_complete_data_full[s*2048+:2048]),.o_complete_mask(o_complete_mask[s*256+:256]),
   .o_mem_valid(o_mem_valid[s]),.i_mem_ready(i_mem_ready[s]),.o_mem_slot(o_mem_slot[s*2+:2]),.o_mem_address(o_mem_address[s*57+:57]),.o_mem_length(o_mem_length[s*6+:6]),.o_mem_attr(o_mem_attr[s*8+:8]),.o_mem_asi(o_mem_asi[s*2+:2]),.o_mem_metadata(o_mem_metadata[s*8+:8]),.i_mem_result_valid(i_mem_result_valid[s]),.o_mem_result_ready(o_mem_result_ready[s]),.i_mem_result_slot(i_mem_result_slot[s*2+:2]),.i_mem_result_data(i_mem_result_data[s*512+:512]),.i_mem_result_status(i_mem_result_status[s*4+:4]),.i_mem_result_data_full(i_mem_result_data_full[s*2048+:2048]),.o_mem_be(o_mem_be[s*256+:256]),
   .o_write_mem_valid(o_write_mem_valid[s]),.i_write_mem_ready(i_write_mem_ready[s]),.o_write_mem_slot(o_write_mem_slot[s*2+:2]),.o_write_mem_address(o_write_mem_address[s*57+:57]),.o_write_mem_length(o_write_mem_length[s*6+:6]),.o_write_mem_attr(o_write_mem_attr[s*8+:8]),.o_write_mem_asi(o_write_mem_asi[s*2+:2]),.o_write_mem_metadata(o_write_mem_metadata[s*8+:8]),.o_write_mem_data(o_write_mem_data[s*2048+:2048]),.o_write_mem_be(o_write_mem_be[s*256+:256]),.i_write_mem_result_valid(i_write_mem_result_valid[s]),.o_write_mem_result_ready(o_write_mem_result_ready[s]),.i_write_mem_result_slot(i_write_mem_result_slot[s*2+:2]),.i_write_mem_result_status(i_write_mem_result_status[s*4+:4]),.o_write_completer_count(o_write_completer_count[s*8+:8]),
   .i_atomic_profile_valid(i_atomic_profile_valid[s*32+:32]),.i_atomic_two_operand(i_atomic_two_operand[s*32+:32]),.i_atomic_order_profile_valid(i_atomic_order_profile_valid[s]),.i_atomic_order_mode(i_atomic_order_mode[s*2+:2]),.i_atomic_order_epoch(i_atomic_order_epoch[s*8+:8]),.o_atomic_backend_valid(o_atomic_backend_valid[s*4+:4]),.i_atomic_backend_ready(i_atomic_backend_ready[s*4+:4]),.o_atomic_backend_token(o_atomic_backend_token[s*4*ATOMIC_TOKEN_WIDTH+:4*ATOMIC_TOKEN_WIDTH]),.o_atomic_backend_header(o_atomic_backend_header[s*512+:512]),.o_atomic_backend_port(o_atomic_backend_port[s*8+:8]),.o_atomic_backend_operands(o_atomic_backend_operands[s*2048+:2048]),.o_atomic_backend_byte_enable(o_atomic_backend_byte_enable[s*1024+:1024]),.o_atomic_backend_atomic_return(o_atomic_backend_atomic_return[s*4+:4]),.o_atomic_backend_op_type(o_atomic_backend_op_type[s*20+:20]),.o_atomic_backend_op_size(o_atomic_backend_op_size[s*8+:8]),.i_atomic_backend_result_valid(i_atomic_backend_result_valid[s*4+:4]),.o_atomic_backend_result_ready(o_atomic_backend_result_ready[s*4+:4]),.i_atomic_backend_result_token(i_atomic_backend_result_token[s*4*ATOMIC_TOKEN_WIDTH+:4*ATOMIC_TOKEN_WIDTH]),.i_atomic_backend_result_status(i_atomic_backend_result_status[s*16+:16]),.i_atomic_backend_result_data(i_atomic_backend_result_data[s*2048+:2048]),.o_atomic_response_valid(o_atomic_response_valid[s*4+:4]),.i_atomic_response_ready(i_atomic_response_ready[s*4+:4]),.o_atomic_response_token(o_atomic_response_token[s*4*ATOMIC_TOKEN_WIDTH+:4*ATOMIC_TOKEN_WIDTH]),.o_atomic_response_atomic_return(o_atomic_response_atomic_return[s*4+:4]),.o_atomic_response_port(o_atomic_response_port[s*8+:8]),.o_atomic_response_tag(o_atomic_response_tag[s*44+:44]),.o_atomic_response_src(o_atomic_response_src[s*40+:40]),.o_atomic_response_dst(o_atomic_response_dst[s*40+:40]),.o_atomic_response_status(o_atomic_response_status[s*16+:16]),.o_atomic_response_data(o_atomic_response_data[s*2048+:2048]),.o_atomic_response_data_valid(o_atomic_response_data_valid[s*4+:4]),
   .o_message_backend_valid(o_message_backend_valid[s]),.i_message_backend_ready(i_message_backend_ready[s]),.o_message_backend_token(o_message_backend_token[s*MESSAGE_TOKEN_WIDTH+:MESSAGE_TOKEN_WIDTH]),.o_message_backend_header(o_message_backend_header[s*128+:128]),.o_message_backend_port(o_message_backend_port[s*2+:2]),.o_message_backend_data(o_message_backend_data[s*2048+:2048]),.o_message_backend_be(o_message_backend_be[s*256+:256]),
   .i_message_result_valid(i_message_result_valid[s]),.o_message_result_ready(o_message_result_ready[s]),.i_message_result_token(i_message_result_token[s*MESSAGE_TOKEN_WIDTH+:MESSAGE_TOKEN_WIDTH]),.i_message_result_is_read(i_message_result_is_read[s]),.i_message_result_num_beats(i_message_result_num_beats[s*2+:2]),.i_message_result_status(i_message_result_status[s*4+:4]),.i_message_result_data(i_message_result_data[s*2048+:2048]),.i_message_result_poison(i_message_result_poison[s*4+:4]),.o_message_busy(o_message_busy[s]),.o_message_reason(o_message_reason[s*8+:8]),
   .o_start_ready(o_start_ready[s*4+:4]),.o_start_taken(o_start_taken[s*4+:4]),.o_local_done(o_local_done[s*4+:4]),.o_peer_done(o_peer_done[s*4+:4]),.o_port_error(o_port_error[s*4+:4]),.o_remote_request_reject_pulse(o_remote_request_reject_pulse[s*4+:4]),.o_transaction_error(o_transaction_error[s]),.o_scheduled_error(o_scheduled_error[s]),.o_busy(o_station_busy[s]),.o_quiescent(o_station_quiescent[s]),.o_error(o_station_error[s]),.o_ras_owner_ready(o_ras_owner_ready[s*3+:3]),.o_ras_missing_owners(o_ras_missing_owners[s*3+:3]));
 end end end else begin:gen_illegal
  assign o_native_boundary_take='b0;assign o_remote_request_reject_pulse='b0;assign o_mode_commit_accept='b0;assign o_mode_error='b0;assign o_active_mode='b0;assign o_active_mask='b0;assign o_port_slot_enable='b0;assign o_slot_port='b0;assign o_slot_error='b0;assign o_rate_ready='b0;assign o_rate_accept='b0;assign o_rate_error='b0;assign o_rate_configured='b0;assign o_active_rate_code='b0;assign o_rx_frame_ready='b0;assign o_tx_control_valid='b0;assign o_tx_control_replay_request='b0;assign o_tx_control_target='b0;assign o_crc_input_valid='b0;assign o_crc_input_data='b0;assign o_crc_input_sop='b0;assign o_crc_input_eop='b0;assign o_crc_input_sequence='b0;assign o_crc_input_replay='b0;assign o_crc_required='b0;assign o_physical_valid='b0;assign o_tx_resident_count='b0;assign o_ras_owner_ready='b0;assign o_ras_missing_owners={C_FLAT_STATIONS*3{1'b1}};
  assign o_request_ready='b0;assign o_order_busy='b0;assign o_order_quiescent='b0;assign o_order_error='b0;assign o_complete_valid='b0;assign o_complete_port='b0;assign o_complete_tag='b0;assign o_complete_status='b0;assign o_complete_data='b0;assign o_complete_data_valid='b0;assign o_complete_is_write='b0;assign o_complete_data_full='b0;assign o_complete_mask='b0;assign o_mem_valid='b0;assign o_mem_slot='b0;assign o_mem_address='b0;assign o_mem_length='b0;assign o_mem_attr='b0;assign o_mem_asi='b0;assign o_mem_metadata='b0;assign o_mem_result_ready='b0;assign o_mem_be='b0;assign o_write_mem_valid='b0;assign o_write_mem_slot='b0;assign o_write_mem_address='b0;assign o_write_mem_length='b0;assign o_write_mem_attr='b0;assign o_write_mem_asi='b0;assign o_write_mem_metadata='b0;assign o_write_mem_data='b0;assign o_write_mem_be='b0;assign o_write_mem_result_ready='b0;assign o_write_completer_count='b0;assign o_atomic_backend_valid='b0;assign o_atomic_backend_token='b0;assign o_atomic_backend_header='b0;assign o_atomic_backend_port='b0;assign o_atomic_backend_operands='b0;assign o_atomic_backend_byte_enable='b0;assign o_atomic_backend_atomic_return='b0;assign o_atomic_backend_op_type='b0;assign o_atomic_backend_op_size='b0;assign o_atomic_backend_result_ready='b0;assign o_atomic_response_valid='b0;assign o_atomic_response_token='b0;assign o_atomic_response_atomic_return='b0;assign o_atomic_response_port='b0;assign o_atomic_response_tag='b0;assign o_atomic_response_src='b0;assign o_atomic_response_dst='b0;assign o_atomic_response_status='b0;assign o_atomic_response_data='b0;assign o_atomic_response_data_valid='b0;assign o_message_backend_valid='b0;assign o_message_backend_token='b0;assign o_message_backend_header='b0;assign o_message_backend_port='b0;assign o_message_backend_data='b0;assign o_message_backend_be='b0;assign o_message_result_ready='b0;assign o_message_busy='b0;assign o_message_reason='b0;assign o_start_ready='b0;assign o_start_taken='b0;assign o_local_done='b0;assign o_peer_done='b0;assign o_port_error='b0;assign o_transaction_error='b0;assign o_scheduled_error='b0;assign o_station_busy='b0;assign o_station_quiescent='b0;assign o_station_error='b0;
 end endgenerate
endmodule
`default_nettype wire
