`timescale 1ns/1ps
`default_nettype none
// 统一managed transaction发布候选：CSR唯一拥有requested mode和逐端口link-reset命令，
// transaction Station array返回真实active mode、busy/quiescent和错误。每Station仍只有
// 一个单站composer、四个tl_port及四个DL sequence/replay owner；A19保持physical失败关闭。
module ualink_endpoint_transaction_station_managed_top #(
 parameter integer C_NUM_STATIONS=2,parameter integer C_FLAT_STATIONS=(C_NUM_STATIONS<1)?1:C_NUM_STATIONS,
 parameter integer WIDTH=8,parameter integer HEADER_DEPTH=2,parameter integer BANK_DEPTH=3,parameter integer RX_DEPTH=40,
 parameter integer ORIGINATOR_CAPACITY=4,parameter integer COMPLETER_CAPACITY=4,parameter integer MESSAGE_ENABLE=0,parameter integer MODE_RECONFIG_CLOSE_ENABLE=1,parameter integer RATE_RECONFIG_CLOSE_ENABLE=0,parameter integer RATE_ACK_TIMEOUT_CYCLES=64,parameter integer RAS_EPOCH_RECOVERY_ENABLE=0,parameter integer RAS_EPOCH_WIDTH=8,parameter integer MESSAGE_TOKEN_WIDTH=16,parameter integer NORMAL_WRITE_ENABLE=1,parameter integer FULL_READ_ENABLE=1,parameter integer ATOMIC_ENABLE=1,parameter integer ATOMIC_TX_CLOSE_ENABLE=ATOMIC_ENABLE,parameter integer ATOMIC_TOKEN_WIDTH=16,parameter integer ORDINARY_ORDERING_ENABLE=0,parameter integer REPLAY_DEPTH=4,parameter integer EXPLICIT_PACKET_BOUNDARY_ENABLE=0,parameter integer INTERNAL_PACKET_BOUNDARY_ENABLE=1,
 parameter integer REPLAY_ADDR_WIDTH=(REPLAY_DEPTH<=2)?1:(REPLAY_DEPTH<=4)?2:(REPLAY_DEPTH<=8)?3:(REPLAY_DEPTH<=16)?4:(REPLAY_DEPTH<=32)?5:(REPLAY_DEPTH<=64)?6:(REPLAY_DEPTH<=128)?7:8
)(
 input wire i_clk,input wire i_rstn,input wire i_enable,input wire i_csr_req_valid,output wire o_csr_req_ready,input wire i_csr_req_write,input wire[15:0] i_csr_req_addr,input wire[31:0] i_csr_req_wdata,output wire o_csr_rsp_valid,input wire i_csr_rsp_ready,output wire[31:0] o_csr_rsp_rdata,output wire o_csr_rsp_error,output wire o_csr_rsp_unsupported,
 input wire[C_FLAT_STATIONS-1:0] i_ras_close_valid,output wire[C_FLAT_STATIONS-1:0] o_ras_close_ready,input wire[C_FLAT_STATIONS*RAS_EPOCH_WIDTH-1:0] i_ras_close_epoch,input wire[C_FLAT_STATIONS-1:0] i_ras_cleanup_valid,output wire[C_FLAT_STATIONS-1:0] o_ras_cleanup_ready,input wire[C_FLAT_STATIONS-1:0] i_ras_recover_valid,input wire[C_FLAT_STATIONS*RAS_EPOCH_WIDTH-1:0] i_ras_recover_epoch,
 input wire[C_FLAT_STATIONS*4-1:0] i_lane_up,output wire[C_FLAT_STATIONS*2-1:0] o_requested_mode,output wire[C_FLAT_STATIONS-1:0] o_mode_commit,output wire[C_FLAT_STATIONS*4-1:0] o_port_link_reset,
 input wire[C_FLAT_STATIONS*4-1:0] i_start,input wire[C_FLAT_STATIONS*4-1:0] i_shared,input wire[C_FLAT_STATIONS*80*WIDTH-1:0] i_capacities,input wire[C_FLAT_STATIONS*4-1:0] i_native_sop,input wire[C_FLAT_STATIONS*4-1:0] i_native_eop,output wire[C_FLAT_STATIONS*4-1:0] o_native_boundary_take,
 output wire[C_FLAT_STATIONS-1:0] o_mode_commit_accept,output wire[C_FLAT_STATIONS-1:0] o_mode_error,output wire[C_FLAT_STATIONS*2-1:0] o_active_mode,output wire[C_FLAT_STATIONS*4-1:0] o_active_mask,output wire[C_FLAT_STATIONS*4-1:0] o_port_slot_enable,output wire[C_FLAT_STATIONS*2-1:0] o_slot_port,output wire[C_FLAT_STATIONS-1:0] o_slot_error,
 input wire[C_FLAT_STATIONS*4-1:0] i_rate_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rate_ready,input wire[C_FLAT_STATIONS*64-1:0] i_rate_code,output wire[C_FLAT_STATIONS*4-1:0] o_rate_accept,output wire[C_FLAT_STATIONS*4-1:0] o_rate_error,output wire[C_FLAT_STATIONS*4-1:0] o_rate_configured,output wire[C_FLAT_STATIONS*64-1:0] o_active_rate_code,input wire[C_FLAT_STATIONS*4-1:0] i_tx_budget_available,
 input wire[C_FLAT_STATIONS-1:0] i_rate_reconfig_valid,output wire[C_FLAT_STATIONS-1:0] o_rate_reconfig_ready,output wire[C_FLAT_STATIONS-1:0] o_rate_reconfig_accept,output wire[C_FLAT_STATIONS-1:0] o_rate_reconfig_reject,output wire[C_FLAT_STATIONS-1:0] o_rate_drain_request,output wire[C_FLAT_STATIONS-1:0] o_rate_admission_enable,
 input wire[C_FLAT_STATIONS*4-1:0] i_rate_requested_legal,output wire[C_FLAT_STATIONS*4-1:0] o_rate_notify_valid,input wire[C_FLAT_STATIONS*4-1:0] i_rate_notify_ready,output wire[C_FLAT_STATIONS*64-1:0] o_rate_notify_code,input wire[C_FLAT_STATIONS*4-1:0] i_rate_notify_ack_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rate_notify_ack_ready,input wire[C_FLAT_STATIONS*4-1:0] i_rate_notify_ack_success,input wire[C_FLAT_STATIONS*64-1:0] i_rate_notify_ack_code,output wire[C_FLAT_STATIONS-1:0] o_rate_timeout_error,output wire[C_FLAT_STATIONS-1:0] o_rate_protocol_error,
 input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_valid,output wire[C_FLAT_STATIONS*4-1:0] o_rx_frame_ready,input wire[C_FLAT_STATIONS*2048-1:0] i_rx_frame_data,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_sop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_frame_eop,input wire[C_FLAT_STATIONS*4-1:0] i_rx_fec_complete,input wire[C_FLAT_STATIONS*4-1:0] i_rx_crc_ok,
 output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_valid,input wire[C_FLAT_STATIONS*4-1:0] i_tx_control_ready,output wire[C_FLAT_STATIONS*4-1:0] o_tx_control_replay_request,output wire[C_FLAT_STATIONS*36-1:0] o_tx_control_target,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_valid,input wire[C_FLAT_STATIONS*4-1:0] i_crc_input_ready,output wire[C_FLAT_STATIONS*2048-1:0] o_crc_input_data,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_sop,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_eop,output wire[C_FLAT_STATIONS*36-1:0] o_crc_input_sequence,output wire[C_FLAT_STATIONS*4-1:0] o_crc_input_replay,output wire[C_FLAT_STATIONS*4-1:0] o_crc_required,output wire[C_FLAT_STATIONS*4-1:0] o_physical_valid,output wire[C_FLAT_STATIONS*32-1:0] o_tx_resident_count,
 input wire[C_FLAT_STATIONS*10-1:0] i_local_id,input wire[C_FLAT_STATIONS-1:0] i_request_valid,output wire[C_FLAT_STATIONS-1:0] o_request_ready,input wire[C_FLAT_STATIONS*2-1:0] i_request_port,input wire[C_FLAT_STATIONS*11-1:0] i_request_tag,input wire[C_FLAT_STATIONS*57-1:0] i_request_address,input wire[C_FLAT_STATIONS*10-1:0] i_request_dst,input wire[C_FLAT_STATIONS*6-1:0] i_request_length,input wire[C_FLAT_STATIONS*8-1:0] i_request_attr,
 input wire[C_FLAT_STATIONS-1:0] i_request_is_write,input wire[C_FLAT_STATIONS-1:0] i_request_full,input wire[C_FLAT_STATIONS*2-1:0] i_request_asi,input wire[C_FLAT_STATIONS*8-1:0] i_request_metadata,input wire[C_FLAT_STATIONS*2048-1:0] i_request_data,input wire[C_FLAT_STATIONS*256-1:0] i_request_be,
 input wire[C_FLAT_STATIONS*4-1:0] i_order_profile_valid,input wire[C_FLAT_STATIONS*8-1:0] i_order_mode,input wire[C_FLAT_STATIONS*32-1:0] i_order_epoch,input wire[C_FLAT_STATIONS*4-1:0] i_order_affinity_valid,input wire[C_FLAT_STATIONS*8-1:0] i_order_actual_vc,output wire[C_FLAT_STATIONS*4-1:0] o_order_busy,output wire[C_FLAT_STATIONS*4-1:0] o_order_quiescent,output wire[C_FLAT_STATIONS*4-1:0] o_order_error,
 output wire[C_FLAT_STATIONS-1:0] o_complete_valid,input wire[C_FLAT_STATIONS-1:0] i_complete_ready,output wire[C_FLAT_STATIONS*2-1:0] o_complete_port,output wire[C_FLAT_STATIONS*11-1:0] o_complete_tag,output wire[C_FLAT_STATIONS*4-1:0] o_complete_status,output wire[C_FLAT_STATIONS*512-1:0] o_complete_data,output wire[C_FLAT_STATIONS-1:0] o_complete_data_valid,
 output wire[C_FLAT_STATIONS-1:0] o_complete_is_write,output wire[C_FLAT_STATIONS*2048-1:0] o_complete_data_full,output wire[C_FLAT_STATIONS*256-1:0] o_complete_mask,
 output wire[C_FLAT_STATIONS-1:0] o_mem_valid,input wire[C_FLAT_STATIONS-1:0] i_mem_ready,output wire[C_FLAT_STATIONS*2-1:0] o_mem_slot,output wire[C_FLAT_STATIONS*57-1:0] o_mem_address,output wire[C_FLAT_STATIONS*6-1:0] o_mem_length,output wire[C_FLAT_STATIONS*8-1:0] o_mem_attr,output wire[C_FLAT_STATIONS*2-1:0] o_mem_asi,output wire[C_FLAT_STATIONS*8-1:0] o_mem_metadata,input wire[C_FLAT_STATIONS-1:0] i_mem_result_valid,output wire[C_FLAT_STATIONS-1:0] o_mem_result_ready,input wire[C_FLAT_STATIONS*2-1:0] i_mem_result_slot,input wire[C_FLAT_STATIONS*512-1:0] i_mem_result_data,input wire[C_FLAT_STATIONS*4-1:0] i_mem_result_status,
 input wire[C_FLAT_STATIONS*2048-1:0] i_mem_result_data_full,output wire[C_FLAT_STATIONS*256-1:0] o_mem_be,
 output wire[C_FLAT_STATIONS-1:0] o_write_mem_valid,input wire[C_FLAT_STATIONS-1:0] i_write_mem_ready,output wire[C_FLAT_STATIONS*2-1:0] o_write_mem_slot,output wire[C_FLAT_STATIONS*57-1:0] o_write_mem_address,output wire[C_FLAT_STATIONS*6-1:0] o_write_mem_length,output wire[C_FLAT_STATIONS*8-1:0] o_write_mem_attr,output wire[C_FLAT_STATIONS*2-1:0] o_write_mem_asi,output wire[C_FLAT_STATIONS*8-1:0] o_write_mem_metadata,output wire[C_FLAT_STATIONS*2048-1:0] o_write_mem_data,output wire[C_FLAT_STATIONS*256-1:0] o_write_mem_be,
 input wire[C_FLAT_STATIONS-1:0] i_write_mem_result_valid,output wire[C_FLAT_STATIONS-1:0] o_write_mem_result_ready,input wire[C_FLAT_STATIONS*2-1:0] i_write_mem_result_slot,input wire[C_FLAT_STATIONS*4-1:0] i_write_mem_result_status,output wire[C_FLAT_STATIONS*8-1:0] o_write_completer_count,
 input wire[C_FLAT_STATIONS*32-1:0] i_atomic_profile_valid,input wire[C_FLAT_STATIONS*32-1:0] i_atomic_two_operand,input wire[C_FLAT_STATIONS-1:0] i_atomic_order_profile_valid,input wire[C_FLAT_STATIONS*2-1:0] i_atomic_order_mode,input wire[C_FLAT_STATIONS*8-1:0] i_atomic_order_epoch,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_valid,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_backend_ready,output wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] o_atomic_backend_token,output wire[C_FLAT_STATIONS*512-1:0] o_atomic_backend_header,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_backend_port,output wire[C_FLAT_STATIONS*2048-1:0] o_atomic_backend_operands,output wire[C_FLAT_STATIONS*1024-1:0] o_atomic_backend_byte_enable,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_atomic_return,output wire[C_FLAT_STATIONS*20-1:0] o_atomic_backend_op_type,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_backend_op_size,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_backend_result_valid,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_backend_result_ready,input wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] i_atomic_backend_result_token,input wire[C_FLAT_STATIONS*16-1:0] i_atomic_backend_result_status,input wire[C_FLAT_STATIONS*2048-1:0] i_atomic_backend_result_data,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_valid,input wire[C_FLAT_STATIONS*4-1:0] i_atomic_response_ready,output wire[C_FLAT_STATIONS*4*ATOMIC_TOKEN_WIDTH-1:0] o_atomic_response_token,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_atomic_return,output wire[C_FLAT_STATIONS*8-1:0] o_atomic_response_port,output wire[C_FLAT_STATIONS*44-1:0] o_atomic_response_tag,output wire[C_FLAT_STATIONS*40-1:0] o_atomic_response_src,output wire[C_FLAT_STATIONS*40-1:0] o_atomic_response_dst,output wire[C_FLAT_STATIONS*16-1:0] o_atomic_response_status,output wire[C_FLAT_STATIONS*2048-1:0] o_atomic_response_data,output wire[C_FLAT_STATIONS*4-1:0] o_atomic_response_data_valid,
 output wire[C_FLAT_STATIONS-1:0] o_message_backend_valid,input wire[C_FLAT_STATIONS-1:0] i_message_backend_ready,output wire[C_FLAT_STATIONS*MESSAGE_TOKEN_WIDTH-1:0] o_message_backend_token,output wire[C_FLAT_STATIONS*128-1:0] o_message_backend_header,output wire[C_FLAT_STATIONS*2-1:0] o_message_backend_port,output wire[C_FLAT_STATIONS*2048-1:0] o_message_backend_data,output wire[C_FLAT_STATIONS*256-1:0] o_message_backend_be,
 input wire[C_FLAT_STATIONS-1:0] i_message_result_valid,output wire[C_FLAT_STATIONS-1:0] o_message_result_ready,input wire[C_FLAT_STATIONS*MESSAGE_TOKEN_WIDTH-1:0] i_message_result_token,input wire[C_FLAT_STATIONS-1:0] i_message_result_is_read,input wire[C_FLAT_STATIONS*2-1:0] i_message_result_num_beats,input wire[C_FLAT_STATIONS*4-1:0] i_message_result_status,input wire[C_FLAT_STATIONS*2048-1:0] i_message_result_data,input wire[C_FLAT_STATIONS*4-1:0] i_message_result_poison,output wire[C_FLAT_STATIONS-1:0] o_message_busy,output wire[C_FLAT_STATIONS*8-1:0] o_message_reason,
 output wire[C_FLAT_STATIONS*4-1:0] o_start_ready,output wire[C_FLAT_STATIONS*4-1:0] o_start_taken,output wire[C_FLAT_STATIONS*4-1:0] o_local_done,output wire[C_FLAT_STATIONS*4-1:0] o_peer_done,output wire[C_FLAT_STATIONS*4-1:0] o_port_error,output wire[C_FLAT_STATIONS*4-1:0] o_remote_request_reject_pulse,output wire[C_FLAT_STATIONS*4-1:0] o_remote_request_reject_sticky,output wire[C_FLAT_STATIONS-1:0] o_transaction_error,output wire[C_FLAT_STATIONS-1:0] o_scheduled_error,output wire[C_FLAT_STATIONS-1:0] o_station_busy,output wire[C_FLAT_STATIONS-1:0] o_station_quiescent,output wire[C_FLAT_STATIONS-1:0] o_station_error,output wire[C_FLAT_STATIONS*3-1:0] o_ras_owner_ready,output wire[C_FLAT_STATIONS*3-1:0] o_ras_missing_owners,
 output wire[C_FLAT_STATIONS-1:0] o_ras_recover_ready,output wire[C_FLAT_STATIONS-1:0] o_ras_recovered,output wire[C_FLAT_STATIONS-1:0] o_ras_isolated,output wire[C_FLAT_STATIONS*RAS_EPOCH_WIDTH-1:0] o_ras_epoch,output wire[C_FLAT_STATIONS-1:0] o_ras_certificate,output wire[C_FLAT_STATIONS*RAS_EPOCH_WIDTH-1:0] o_ras_certificate_epoch,output wire[C_FLAT_STATIONS-1:0] o_ras_owner_error,
 output wire o_busy,output wire o_quiescent,output wire o_csr_error_sticky,output wire o_security_unsupported,output wire o_config_error,output wire o_error
);
 wire array_config_error,array_error,csr_config_error,csr_error,managed_error,mode_param_error,rate_param_error,ras_param_error;wire[C_FLAT_STATIONS-1:0] csr_mode_commit,array_mode_error,array_station_error,commit_reject_pulse,commit_reject_sticky;
 wire[C_FLAT_STATIONS-1:0] mode_admission,mode_owner_busy,mode_owner_quiescent,mode_owner_error,mode_request_ready,mode_request_accept;
 wire[C_FLAT_STATIONS-1:0] ras_admission,ras_rx_cleanup;
 wire[C_FLAT_STATIONS-1:0] rate_owner_busy,rate_owner_quiescent,rate_owner_error,rate_gated_request_valid,rate_admission_ready,remote_request_admission;
 wire[C_FLAT_STATIONS*4-1:0] csr_port_link_reset,mode_link_reset,mode_reinit_start,ras_admission_ports;
 wire[C_FLAT_STATIONS*4-1:0] effective_start,gated_rx_frame_valid,array_rx_frame_ready,array_rate_ready,array_rate_accept,array_rate_error,array_rate_configured,managed_apply_valid;
 wire[C_FLAT_STATIONS*64-1:0] array_active_rate_code,managed_apply_code;wire[C_FLAT_STATIONS-1:0] array_request_ready,array_station_busy;
 wire[C_FLAT_STATIONS-1:0] gated_request_valid;
 wire[C_FLAT_STATIONS-1:0] gated_request_is_write;
 assign gated_request_valid=i_request_valid&mode_admission&ras_admission;
 assign o_station_busy=array_station_busy|mode_owner_busy|o_ras_isolated|rate_owner_busy;assign o_busy=i_rstn&&(|o_station_busy);assign o_quiescent=i_rstn&&(&o_station_quiescent)&&(&mode_owner_quiescent)&&(&rate_owner_quiescent)&&!(|o_ras_isolated);assign mode_param_error=(MODE_RECONFIG_CLOSE_ENABLE!=0)&&(MODE_RECONFIG_CLOSE_ENABLE!=1);assign rate_param_error=(RATE_RECONFIG_CLOSE_ENABLE!=0)&&(RATE_RECONFIG_CLOSE_ENABLE!=1);assign ras_param_error=(RAS_EPOCH_RECOVERY_ENABLE!=0)&&(RAS_EPOCH_RECOVERY_ENABLE!=1);assign o_config_error=array_config_error||csr_config_error||mode_param_error||rate_param_error||ras_param_error;assign managed_error=array_error||csr_error||o_config_error||(|o_slot_error)||(|commit_reject_sticky)||(|mode_owner_error)||(|rate_owner_error)||(|o_ras_owner_error);assign o_error=managed_error;
 endpoint_station_csr_window #(.C_NUM_STATIONS(C_NUM_STATIONS),.C_FLAT_STATIONS(C_FLAT_STATIONS))u_csr(
  .i_clk(i_clk),.i_rstn(i_rstn),.i_req_valid(i_csr_req_valid),.o_req_ready(o_csr_req_ready),.i_req_write(i_csr_req_write),.i_req_addr(i_csr_req_addr),.i_req_wdata(i_csr_req_wdata),.o_rsp_valid(o_csr_rsp_valid),.i_rsp_ready(i_csr_rsp_ready),.o_rsp_rdata(o_csr_rsp_rdata),.o_rsp_error(o_csr_rsp_error),.o_rsp_unsupported(o_csr_rsp_unsupported),.o_requested_mode(o_requested_mode),.o_mode_commit(csr_mode_commit),.o_port_link_reset(csr_port_link_reset),.i_active_mode(o_active_mode),.i_active_mask(o_active_mask),.i_station_busy(o_station_busy),.i_station_quiescent(o_station_quiescent),.i_station_error(o_station_error),.i_global_busy(o_busy),.i_global_quiescent(o_quiescent),.i_global_error(managed_error),.i_request_reject_pulse(o_remote_request_reject_pulse),.o_request_reject_sticky(o_remote_request_reject_sticky),.o_error_sticky(o_csr_error_sticky),.o_unsupported_security(o_security_unsupported),.o_config_error(csr_config_error),.o_error(csr_error));
 generate if(MODE_RECONFIG_CLOSE_ENABLE==1)begin:gen_mode_close
  endpoint_station_mode_reconfiguration_array #(.C_NUM_STATIONS(C_NUM_STATIONS),.C_FLAT_STATIONS(C_FLAT_STATIONS))u_mode_owner(
   .i_clk(i_clk),.i_rstn(i_rstn),.i_enable(i_enable),.i_request_valid(csr_mode_commit),.o_request_ready(mode_request_ready),.i_requested_mode(o_requested_mode),
   .i_station_quiescent(o_station_quiescent),.i_lane_up(i_lane_up),.i_mode_commit_accept(o_mode_commit_accept),.i_active_mode(o_active_mode),.i_active_mask(o_active_mask),
   .i_local_done(o_local_done),.i_peer_done(o_peer_done),.i_external_link_reset(csr_port_link_reset),.o_request_accept(mode_request_accept),.o_request_reject(commit_reject_pulse),
   .o_admission_enable(mode_admission),.o_link_reset(mode_link_reset),.o_mode_commit(o_mode_commit),.o_reinit_start(mode_reinit_start),
   .o_busy(mode_owner_busy),.o_quiescent(mode_owner_quiescent),.o_error(mode_owner_error));
  assign commit_reject_sticky=mode_owner_error;
 end else if(MODE_RECONFIG_CLOSE_ENABLE==0)begin:gen_mode_legacy
  endpoint_station_mode_commit_admission #(.C_STATIONS(C_FLAT_STATIONS))u_commit_admission(.i_clk(i_clk),.i_rstn(i_rstn),.i_commit(csr_mode_commit),.i_station_busy(o_station_busy),.o_admitted_commit(o_mode_commit),.o_reject_pulse(commit_reject_pulse),.o_reject_sticky(commit_reject_sticky));
  assign mode_admission={C_FLAT_STATIONS{1'b1}};assign mode_link_reset={(C_FLAT_STATIONS*4){1'b0}};assign mode_reinit_start={(C_FLAT_STATIONS*4){1'b0}};assign mode_owner_busy={C_FLAT_STATIONS{1'b0}};assign mode_owner_quiescent={C_FLAT_STATIONS{1'b1}};assign mode_owner_error={C_FLAT_STATIONS{1'b0}};assign mode_request_ready={C_FLAT_STATIONS{1'b0}};assign mode_request_accept={C_FLAT_STATIONS{1'b0}};
 end else begin:gen_mode_illegal
  assign o_mode_commit={C_FLAT_STATIONS{1'b0}};assign commit_reject_pulse={C_FLAT_STATIONS{1'b0}};assign commit_reject_sticky={C_FLAT_STATIONS{1'b1}};
  assign mode_admission={C_FLAT_STATIONS{1'b0}};assign mode_link_reset={(C_FLAT_STATIONS*4){1'b0}};assign mode_reinit_start={(C_FLAT_STATIONS*4){1'b0}};assign mode_owner_busy={C_FLAT_STATIONS{1'b0}};assign mode_owner_quiescent={C_FLAT_STATIONS{1'b0}};assign mode_owner_error={C_FLAT_STATIONS{1'b1}};assign mode_request_ready={C_FLAT_STATIONS{1'b0}};assign mode_request_accept={C_FLAT_STATIONS{1'b0}};
 end endgenerate
 genvar ras_station;generate if(RAS_EPOCH_RECOVERY_ENABLE==1)begin:gen_ras_epoch
  for(ras_station=0;ras_station<32'd256;ras_station=ras_station+32'd1)begin:gen_station if(ras_station<C_FLAT_STATIONS)begin:gen_present
   endpoint_station_managed_epoch_owner #(.EPOCH_WIDTH(RAS_EPOCH_WIDTH))u_owner(
    .i_clk(i_clk),.i_rstn(i_rstn),.i_enable(i_enable),.i_close_valid(i_ras_close_valid[ras_station]),.o_close_ready(o_ras_close_ready[ras_station]),.i_close_epoch(i_ras_close_epoch[ras_station*RAS_EPOCH_WIDTH+:RAS_EPOCH_WIDTH]),
    .i_cleanup_valid(i_ras_cleanup_valid[ras_station]),.o_cleanup_ready(o_ras_cleanup_ready[ras_station]),.o_rx_cleanup_pulse(ras_rx_cleanup[ras_station]),
    .i_recover_valid(i_ras_recover_valid[ras_station]),.i_recover_epoch(i_ras_recover_epoch[ras_station*RAS_EPOCH_WIDTH+:RAS_EPOCH_WIDTH]),.o_recover_ready(o_ras_recover_ready[ras_station]),.o_recovered(o_ras_recovered[ras_station]),
    .i_station_quiescent(o_station_quiescent[ras_station]),.i_station_error(o_station_error[ras_station]),.i_owner_ready(o_ras_owner_ready[ras_station*3+:3]),
    .o_admission_enable(ras_admission[ras_station]),.o_isolated(o_ras_isolated[ras_station]),.o_epoch(o_ras_epoch[ras_station*RAS_EPOCH_WIDTH+:RAS_EPOCH_WIDTH]),.o_certificate(o_ras_certificate[ras_station]),.o_certificate_epoch(o_ras_certificate_epoch[ras_station*RAS_EPOCH_WIDTH+:RAS_EPOCH_WIDTH]),.o_error(o_ras_owner_error[ras_station]));
  end end
 end else if(RAS_EPOCH_RECOVERY_ENABLE==0)begin:gen_ras_disabled
  assign o_ras_close_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_cleanup_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_recover_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_recovered={C_FLAT_STATIONS{1'b0}};assign o_ras_isolated={C_FLAT_STATIONS{1'b0}};assign o_ras_epoch={(C_FLAT_STATIONS*RAS_EPOCH_WIDTH){1'b0}};assign o_ras_certificate={C_FLAT_STATIONS{1'b0}};assign o_ras_certificate_epoch={(C_FLAT_STATIONS*RAS_EPOCH_WIDTH){1'b0}};assign o_ras_owner_error={C_FLAT_STATIONS{1'b0}};assign ras_admission={C_FLAT_STATIONS{1'b1}};assign ras_rx_cleanup={C_FLAT_STATIONS{1'b0}};
 end else begin:gen_ras_illegal
  assign o_ras_close_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_cleanup_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_recover_ready={C_FLAT_STATIONS{1'b0}};assign o_ras_recovered={C_FLAT_STATIONS{1'b0}};assign o_ras_isolated={C_FLAT_STATIONS{1'b1}};assign o_ras_epoch={(C_FLAT_STATIONS*RAS_EPOCH_WIDTH){1'b0}};assign o_ras_certificate={C_FLAT_STATIONS{1'b0}};assign o_ras_certificate_epoch={(C_FLAT_STATIONS*RAS_EPOCH_WIDTH){1'b0}};assign o_ras_owner_error={C_FLAT_STATIONS{1'b1}};assign ras_admission={C_FLAT_STATIONS{1'b0}};assign ras_rx_cleanup={C_FLAT_STATIONS{1'b0}};
 end endgenerate
 generate if(RATE_RECONFIG_CLOSE_ENABLE==1)begin:gen_rate_close
  endpoint_station_rate_managed_admission_gate #(.C_NUM_STATIONS(C_NUM_STATIONS),.C_FLAT_STATIONS(C_FLAT_STATIONS),.C_RATE_WIDTH(16),.C_ADMISSION_PAYLOAD_WIDTH(1),.C_ACK_TIMEOUT_CYCLES(RATE_ACK_TIMEOUT_CYCLES))u_rate_gate(
   .i_clk(i_clk),.i_rstn(i_rstn),.i_enable(i_enable),.i_rate_request_valid(i_rate_reconfig_valid),.o_rate_request_ready(o_rate_reconfig_ready),
   .i_active_mask(o_active_mask),.i_requested_rate_code(i_rate_code),.i_requested_rate_legal(i_rate_requested_legal),.i_station_quiescent(o_station_quiescent),.i_station_busy(array_station_busy),.i_port_link_reset(o_port_link_reset),
   .o_rate_request_accept(o_rate_reconfig_accept),.o_rate_request_reject(o_rate_reconfig_reject),.o_rate_drain_request(o_rate_drain_request),.o_rate_admission_enable(o_rate_admission_enable),
   .o_notify_valid(o_rate_notify_valid),.i_notify_ready(i_rate_notify_ready),.o_notify_rate_code(o_rate_notify_code),.i_notify_ack_valid(i_rate_notify_ack_valid),.o_notify_ack_ready(o_rate_notify_ack_ready),.i_notify_ack_success(i_rate_notify_ack_success),.i_notify_ack_rate_code(i_rate_notify_ack_code),
   .o_pacing_rate_valid(managed_apply_valid),.i_pacing_rate_ready(array_rate_ready),.o_pacing_rate_code(managed_apply_code),.i_pacing_rate_accept(array_rate_accept),.i_pacing_rate_error(array_rate_error),.o_rate_configured(o_rate_configured),.o_active_rate_code(o_active_rate_code),
   .i_admission_valid(gated_request_valid),.o_admission_ready(rate_admission_ready),.i_admission_payload(i_request_is_write),.o_downstream_valid(rate_gated_request_valid),.i_downstream_ready(array_request_ready&mode_admission&ras_admission),.o_downstream_payload(gated_request_is_write),
   .o_mode_commit_busy(),.o_owner_busy(rate_owner_busy),.o_owner_quiescent(rate_owner_quiescent),.o_timeout_error(o_rate_timeout_error),.o_protocol_error(o_rate_protocol_error),.o_config_error(),.o_error(rate_owner_error));
  assign o_request_ready=rate_admission_ready;assign o_rate_ready=array_rate_ready;assign o_rate_accept=array_rate_accept;assign o_rate_error=array_rate_error|{4*C_FLAT_STATIONS{|rate_owner_error}};
 end else if(RATE_RECONFIG_CLOSE_ENABLE==0)begin:gen_rate_legacy
  assign managed_apply_valid=i_rate_valid;assign managed_apply_code=i_rate_code;assign o_rate_ready=array_rate_ready;assign o_rate_accept=array_rate_accept;assign o_rate_error=array_rate_error;assign o_rate_configured=array_rate_configured;assign o_active_rate_code=array_active_rate_code;
  assign o_rate_reconfig_ready={C_FLAT_STATIONS{1'b0}};assign o_rate_reconfig_accept={C_FLAT_STATIONS{1'b0}};assign o_rate_reconfig_reject={C_FLAT_STATIONS{1'b0}};assign o_rate_drain_request={C_FLAT_STATIONS{1'b0}};assign o_rate_admission_enable={C_FLAT_STATIONS{1'b1}};
  assign o_rate_notify_valid={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_notify_code={(64*C_FLAT_STATIONS){1'b0}};assign o_rate_notify_ack_ready={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_timeout_error={C_FLAT_STATIONS{1'b0}};assign o_rate_protocol_error={C_FLAT_STATIONS{1'b0}};
  assign rate_owner_busy={C_FLAT_STATIONS{1'b0}};assign rate_owner_quiescent={C_FLAT_STATIONS{1'b1}};assign rate_owner_error={C_FLAT_STATIONS{1'b0}};assign rate_gated_request_valid=gated_request_valid;assign rate_admission_ready=array_request_ready&mode_admission&ras_admission;assign gated_request_is_write=i_request_is_write;assign o_request_ready=rate_admission_ready;
 end else begin:gen_rate_illegal
  assign managed_apply_valid={(4*C_FLAT_STATIONS){1'b0}};assign managed_apply_code={(64*C_FLAT_STATIONS){1'b0}};assign o_rate_ready={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_accept={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_error={(4*C_FLAT_STATIONS){1'b1}};assign o_rate_configured={(4*C_FLAT_STATIONS){1'b0}};assign o_active_rate_code={(64*C_FLAT_STATIONS){1'b0}};
  assign o_rate_reconfig_ready={C_FLAT_STATIONS{1'b0}};assign o_rate_reconfig_accept={C_FLAT_STATIONS{1'b0}};assign o_rate_reconfig_reject={C_FLAT_STATIONS{1'b1}};assign o_rate_drain_request={C_FLAT_STATIONS{1'b0}};assign o_rate_admission_enable={C_FLAT_STATIONS{1'b0}};assign o_rate_notify_valid={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_notify_code={(64*C_FLAT_STATIONS){1'b0}};assign o_rate_notify_ack_ready={(4*C_FLAT_STATIONS){1'b0}};assign o_rate_timeout_error={C_FLAT_STATIONS{1'b0}};assign o_rate_protocol_error={C_FLAT_STATIONS{1'b1}};
  assign rate_owner_busy={C_FLAT_STATIONS{1'b0}};assign rate_owner_quiescent={C_FLAT_STATIONS{1'b0}};assign rate_owner_error={C_FLAT_STATIONS{1'b1}};assign rate_gated_request_valid={C_FLAT_STATIONS{1'b0}};assign rate_admission_ready={C_FLAT_STATIONS{1'b0}};assign gated_request_is_write={C_FLAT_STATIONS{1'b0}};assign o_request_ready={C_FLAT_STATIONS{1'b0}};
 end endgenerate
 genvar mode_station;generate for(mode_station=0;mode_station<32'd256;mode_station=mode_station+32'd1)begin:gen_mode_gate
  if(mode_station<C_FLAT_STATIONS)begin:gen_present
   assign ras_admission_ports[mode_station*4+:4]={4{ras_admission[mode_station]}};
   assign remote_request_admission[mode_station]=mode_admission[mode_station]&o_rate_admission_enable[mode_station]&ras_admission[mode_station];
  end
 end endgenerate
 assign o_port_link_reset=csr_port_link_reset|mode_link_reset;assign effective_start=i_start|mode_reinit_start;
 // drain期继续接收Response、控制及已绑定Data；新远端事务在typed解码处关闭准入。
 assign gated_rx_frame_valid=i_rx_frame_valid&ras_admission_ports;assign o_rx_frame_ready=array_rx_frame_ready&ras_admission_ports;
 ualink_endpoint_transaction_station_array #(.C_NUM_STATIONS(C_NUM_STATIONS),.C_FLAT_STATIONS(C_FLAT_STATIONS),.WIDTH(WIDTH),.HEADER_DEPTH(HEADER_DEPTH),.BANK_DEPTH(BANK_DEPTH),.RX_DEPTH(RX_DEPTH),.ORIGINATOR_CAPACITY(ORIGINATOR_CAPACITY),.COMPLETER_CAPACITY(COMPLETER_CAPACITY),.MESSAGE_ENABLE(MESSAGE_ENABLE),.MESSAGE_TOKEN_WIDTH(MESSAGE_TOKEN_WIDTH),.NORMAL_WRITE_ENABLE(NORMAL_WRITE_ENABLE),.FULL_READ_ENABLE(FULL_READ_ENABLE),.ATOMIC_ENABLE(ATOMIC_ENABLE),.ATOMIC_TX_CLOSE_ENABLE(ATOMIC_TX_CLOSE_ENABLE),.ATOMIC_TOKEN_WIDTH(ATOMIC_TOKEN_WIDTH),.ORDINARY_ORDERING_ENABLE(ORDINARY_ORDERING_ENABLE),.REPLAY_DEPTH(REPLAY_DEPTH),.REPLAY_ADDR_WIDTH(REPLAY_ADDR_WIDTH),.DYNAMIC_MODE_ENABLE(1),.EXPLICIT_PACKET_BOUNDARY_ENABLE(EXPLICIT_PACKET_BOUNDARY_ENABLE),.INTERNAL_PACKET_BOUNDARY_ENABLE(INTERNAL_PACKET_BOUNDARY_ENABLE))u_array(
  .i_clk(i_clk),.i_rstn(i_rstn),.i_enable(i_enable),.i_remote_request_admission_enable(remote_request_admission),.i_ras_rx_cleanup(ras_rx_cleanup),.i_port_link_reset(o_port_link_reset),.i_start(effective_start),.i_shared(i_shared),.i_capacities(i_capacities),.i_native_sop(i_native_sop),.i_native_eop(i_native_eop),.o_native_boundary_take(o_native_boundary_take),.i_requested_mode(o_requested_mode),.i_mode_commit(o_mode_commit),.i_lane_up(i_lane_up),.o_mode_commit_accept(o_mode_commit_accept),.o_mode_error(array_mode_error),.o_active_mode(o_active_mode),.o_active_mask(o_active_mask),.o_port_slot_enable(o_port_slot_enable),.o_slot_port(o_slot_port),.o_slot_error(o_slot_error),
  .i_rate_valid(managed_apply_valid),.o_rate_ready(array_rate_ready),.i_rate_code(managed_apply_code),.o_rate_accept(array_rate_accept),.o_rate_error(array_rate_error),.o_rate_configured(array_rate_configured),.o_active_rate_code(array_active_rate_code),.i_tx_budget_available(i_tx_budget_available),.i_rx_frame_valid(gated_rx_frame_valid),.o_rx_frame_ready(array_rx_frame_ready),.i_rx_frame_data(i_rx_frame_data),.i_rx_frame_sop(i_rx_frame_sop),.i_rx_frame_eop(i_rx_frame_eop),.i_rx_fec_complete(i_rx_fec_complete),.i_rx_crc_ok(i_rx_crc_ok),.o_tx_control_valid(o_tx_control_valid),.i_tx_control_ready(i_tx_control_ready),.o_tx_control_replay_request(o_tx_control_replay_request),.o_tx_control_target(o_tx_control_target),.o_crc_input_valid(o_crc_input_valid),.i_crc_input_ready(i_crc_input_ready),.o_crc_input_data(o_crc_input_data),.o_crc_input_sop(o_crc_input_sop),.o_crc_input_eop(o_crc_input_eop),.o_crc_input_sequence(o_crc_input_sequence),.o_crc_input_replay(o_crc_input_replay),.o_crc_required(o_crc_required),.o_physical_valid(o_physical_valid),.o_tx_resident_count(o_tx_resident_count),
  .i_local_id(i_local_id),.i_request_valid(rate_gated_request_valid),.o_request_ready(array_request_ready),.i_request_port(i_request_port),.i_request_tag(i_request_tag),.i_request_address(i_request_address),.i_request_dst(i_request_dst),.i_request_length(i_request_length),.i_request_attr(i_request_attr),.i_request_is_write(gated_request_is_write),.i_request_full(i_request_full),.i_request_asi(i_request_asi),.i_request_metadata(i_request_metadata),.i_request_data(i_request_data),.i_request_be(i_request_be),.i_order_profile_valid(i_order_profile_valid),.i_order_mode(i_order_mode),.i_order_epoch(i_order_epoch),.i_order_affinity_valid(i_order_affinity_valid),.i_order_actual_vc(i_order_actual_vc),.o_order_busy(o_order_busy),.o_order_quiescent(o_order_quiescent),.o_order_error(o_order_error),.o_complete_valid(o_complete_valid),.i_complete_ready(i_complete_ready),.o_complete_port(o_complete_port),.o_complete_tag(o_complete_tag),.o_complete_status(o_complete_status),.o_complete_data(o_complete_data),.o_complete_data_valid(o_complete_data_valid),.o_complete_is_write(o_complete_is_write),.o_complete_data_full(o_complete_data_full),.o_complete_mask(o_complete_mask),.o_mem_valid(o_mem_valid),.i_mem_ready(i_mem_ready),.o_mem_slot(o_mem_slot),.o_mem_address(o_mem_address),.o_mem_length(o_mem_length),.o_mem_attr(o_mem_attr),.o_mem_asi(o_mem_asi),.o_mem_metadata(o_mem_metadata),.i_mem_result_valid(i_mem_result_valid),.o_mem_result_ready(o_mem_result_ready),.i_mem_result_slot(i_mem_result_slot),.i_mem_result_data(i_mem_result_data),.i_mem_result_status(i_mem_result_status),.i_mem_result_data_full(i_mem_result_data_full),.o_mem_be(o_mem_be),.o_write_mem_valid(o_write_mem_valid),.i_write_mem_ready(i_write_mem_ready),.o_write_mem_slot(o_write_mem_slot),.o_write_mem_address(o_write_mem_address),.o_write_mem_length(o_write_mem_length),.o_write_mem_attr(o_write_mem_attr),.o_write_mem_asi(o_write_mem_asi),.o_write_mem_metadata(o_write_mem_metadata),.o_write_mem_data(o_write_mem_data),.o_write_mem_be(o_write_mem_be),.i_write_mem_result_valid(i_write_mem_result_valid),.o_write_mem_result_ready(o_write_mem_result_ready),.i_write_mem_result_slot(i_write_mem_result_slot),.i_write_mem_result_status(i_write_mem_result_status),.o_write_completer_count(o_write_completer_count),
  .i_atomic_profile_valid(i_atomic_profile_valid),.i_atomic_two_operand(i_atomic_two_operand),.i_atomic_order_profile_valid(i_atomic_order_profile_valid),.i_atomic_order_mode(i_atomic_order_mode),.i_atomic_order_epoch(i_atomic_order_epoch),.o_atomic_backend_valid(o_atomic_backend_valid),.i_atomic_backend_ready(i_atomic_backend_ready),.o_atomic_backend_token(o_atomic_backend_token),.o_atomic_backend_header(o_atomic_backend_header),.o_atomic_backend_port(o_atomic_backend_port),.o_atomic_backend_operands(o_atomic_backend_operands),.o_atomic_backend_byte_enable(o_atomic_backend_byte_enable),.o_atomic_backend_atomic_return(o_atomic_backend_atomic_return),.o_atomic_backend_op_type(o_atomic_backend_op_type),.o_atomic_backend_op_size(o_atomic_backend_op_size),.i_atomic_backend_result_valid(i_atomic_backend_result_valid),.o_atomic_backend_result_ready(o_atomic_backend_result_ready),.i_atomic_backend_result_token(i_atomic_backend_result_token),.i_atomic_backend_result_status(i_atomic_backend_result_status),.i_atomic_backend_result_data(i_atomic_backend_result_data),.o_atomic_response_valid(o_atomic_response_valid),.i_atomic_response_ready(i_atomic_response_ready),.o_atomic_response_token(o_atomic_response_token),.o_atomic_response_atomic_return(o_atomic_response_atomic_return),.o_atomic_response_port(o_atomic_response_port),.o_atomic_response_tag(o_atomic_response_tag),.o_atomic_response_src(o_atomic_response_src),.o_atomic_response_dst(o_atomic_response_dst),.o_atomic_response_status(o_atomic_response_status),.o_atomic_response_data(o_atomic_response_data),.o_atomic_response_data_valid(o_atomic_response_data_valid),
  .o_message_backend_valid(o_message_backend_valid),.i_message_backend_ready(i_message_backend_ready),.o_message_backend_token(o_message_backend_token),.o_message_backend_header(o_message_backend_header),.o_message_backend_port(o_message_backend_port),.o_message_backend_data(o_message_backend_data),.o_message_backend_be(o_message_backend_be),.i_message_result_valid(i_message_result_valid),.o_message_result_ready(o_message_result_ready),.i_message_result_token(i_message_result_token),.i_message_result_is_read(i_message_result_is_read),.i_message_result_num_beats(i_message_result_num_beats),.i_message_result_status(i_message_result_status),.i_message_result_data(i_message_result_data),.i_message_result_poison(i_message_result_poison),.o_message_busy(o_message_busy),.o_message_reason(o_message_reason),
  .o_start_ready(o_start_ready),.o_start_taken(o_start_taken),.o_local_done(o_local_done),.o_peer_done(o_peer_done),.o_port_error(o_port_error),.o_remote_request_reject_pulse(o_remote_request_reject_pulse),.o_transaction_error(o_transaction_error),.o_scheduled_error(o_scheduled_error),.o_station_busy(array_station_busy),.o_station_quiescent(o_station_quiescent),.o_station_error(array_station_error),.o_ras_owner_ready(o_ras_owner_ready),.o_ras_missing_owners(o_ras_missing_owners),.o_config_error(array_config_error),.o_error(array_error));
 wire unused_commit_reject_pulse,unused_mode_status;assign unused_commit_reject_pulse=|commit_reject_pulse;assign unused_mode_status=(|mode_owner_busy)^(|mode_owner_quiescent)^(|mode_request_ready)^(|mode_request_accept);assign o_mode_error=array_mode_error|commit_reject_sticky;assign o_station_error=array_station_error|commit_reject_sticky;
endmodule

`default_nettype wire
