`timescale 1ns/1ps
module dummy_tb;
parameter P=1,C=1,SW=0,E=2,UNIT=0;
reg clk=0;always #5 clk=~clk;
reg rstn;
reg [P-1:0] iso;
reg [P-1:0] down;
reg [P-1:0] up;
reg [P-1:0] init;
reg [P-1:0] drop;
reg quiet;
reg tv;
reg [2-1:0] ts;
reg [2-1:0] tp;
reg [E-1:0] te;
reg [11-1:0] tag;
reg read;
reg [3-1:0] beats;
reg cv;
reg [2-1:0] cs;
reg [E-1:0] ce;
reg rv;
reg [E-1:0] re;
reg rr;
reg dr;
reg qv;
reg [2-1:0] qs;
reg [2-1:0] qp;
reg [E-1:0] qe;
reg [11-1:0] qt;
reg qr;
reg [3-1:0] qb;
reg [4-1:0] qstatus;
wire [P-1:0] isolated;
wire [P-1:0] forward;
wire [E-1:0] epoch;
wire [8-1:0] count;
wire tr;
wire cr;
wire discard;
wire retire;
wire recover_ready;
wire recovered;
wire [4-1:0] error;
wire qready;
wire accepted;
wire busy;
wire response_valid;
wire [2-1:0] response_slot;
wire [2-1:0] response_port;
wire [E-1:0] response_epoch;
wire [11-1:0] response_tag;
wire response_read;
wire [2-1:0] response_num;
wire response_last;
wire [2-1:0] response_offset;
wire [4-1:0] response_status;
wire [512-1:0] response_data;
wire done_valid;
wire [2-1:0] done_slot;
wire [E-1:0] done_epoch;
wire generator_error;
reg [P-1:0] expect_isolated;
reg [P-1:0] expect_forward;
reg [E-1:0] expect_epoch;
reg [8-1:0] expect_count;
reg expect_tr;
reg expect_cr;
reg expect_discard;
reg expect_retire;
reg expect_recover_ready;
reg expect_recovered;
reg [4-1:0] expect_error;
reg expect_qready;
reg expect_accepted;
reg expect_busy;
reg expect_response_valid;
reg [2-1:0] expect_response_slot;
reg [2-1:0] expect_response_port;
reg [E-1:0] expect_response_epoch;
reg [11-1:0] expect_response_tag;
reg expect_response_read;
reg [2-1:0] expect_response_num;
reg expect_response_last;
reg [2-1:0] expect_response_offset;
reg [4-1:0] expect_response_status;
reg [512-1:0] expect_response_data;
reg expect_done_valid;
reg [2-1:0] expect_done_slot;
reg [E-1:0] expect_done_epoch;
reg expect_generator_error;
generate if(UNIT==1)begin:g_unit
ras_dummy_completion #(.EPOCH_WIDTH(E))dut(.i_clk(clk),.i_rstn(rstn),.i_response_ready(rr),.o_response_valid(response_valid),.o_response_slot(response_slot),.o_response_port(response_port),.o_response_epoch(response_epoch),.o_response_tag(response_tag),.o_response_read(response_read),.o_response_num(response_num),.o_response_last(response_last),.o_response_offset(response_offset),.o_response_status(response_status),.o_response_data(response_data),.i_request_valid(qv),.o_request_ready(qready),.i_request_slot(qs),.i_request_port(qp),.i_request_epoch(qe),.i_request_tag(qt),.i_request_read(qr),.i_request_beats(qb),.i_request_status(qstatus),.i_done_ready(dr),.o_done_valid(done_valid),.o_done_slot(done_slot),.o_done_epoch(done_epoch),.o_busy(busy),.o_error(generator_error));
assign accepted=qv&&qready;
assign isolated=0;
assign forward=0;
assign epoch=0;
assign count=0;
assign tr=0;
assign cr=0;
assign discard=0;
assign retire=0;
assign recover_ready=0;
assign recovered=0;
assign error=0;
end else begin:g_path
ras_isolation_completion #(.PORTS(P),.CAPACITY(C),.IS_SWITCH(SW),.EPOCH_WIDTH(E))dut(.i_clk(clk),.i_rstn(rstn),.i_response_ready(rr),.o_response_valid(response_valid),.o_response_slot(response_slot),.o_response_port(response_port),.o_response_epoch(response_epoch),.o_response_tag(response_tag),.o_response_read(response_read),.o_response_num(response_num),.o_response_last(response_last),.o_response_offset(response_offset),.o_response_status(response_status),.o_response_data(response_data),.i_isolate(iso),.i_link_down(down),.i_link_up(up),.i_init_done(init),.i_drop(drop),.i_quiescent(quiet),.i_track_valid(tv),.i_track_slot(ts),.i_track_port(tp),.i_track_epoch(te),.i_track_tag(tag),.i_track_read(read),.i_track_beats(beats),.o_track_ready(tr),.i_complete_valid(cv),.i_complete_slot(cs),.i_complete_epoch(ce),.o_complete_ready(cr),.o_complete_discard(discard),.o_normal_retire(retire),.i_recover_valid(rv),.i_recover_epoch(re),.o_recover_ready(recover_ready),.o_recovered(recovered),.o_isolated(isolated),.o_forward_allowed(forward),.o_epoch(epoch),.o_count(count),.o_error(error),.o_dummy_request_accepted(accepted),.o_dummy_busy(busy),.o_dummy_done_valid(done_valid),.o_dummy_done_slot(done_slot),.o_dummy_done_epoch(done_epoch),.o_generator_error(generator_error));
assign qready=0;
end endgenerate
integer fd,rows,n,rc;reg[2047:0]filename;
initial begin
rstn=0;
iso=0;
down=0;
up=0;
init=0;
drop=0;
quiet=0;
tv=0;
ts=0;
tp=0;
te=0;
tag=0;
read=0;
beats=0;
cv=0;
cs=0;
ce=0;
rv=0;
re=0;
rr=0;
dr=0;
qv=0;
qs=0;
qp=0;
qe=0;
qt=0;
qr=0;
qb=0;
qstatus=0;
if(!$value$plusargs("VECTORS=%s",filename)||!$value$plusargs("ROWS=%d",rows))$fatal(1,"args");
fd=$fopen(filename,"r");if(!fd)$fatal(1,"file");@(posedge clk);#1;
for(n=0;n<rows;n=n+1)begin
@(negedge clk);
rc=$fscanf(fd,"%h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n",rstn,iso,down,up,init,drop,quiet,tv,ts,tp,te,tag,read,beats,cv,cs,ce,rv,re,rr,dr,qv,qs,qp,qe,qt,qr,qb,qstatus,expect_isolated,expect_forward,expect_epoch,expect_count,expect_tr,expect_cr,expect_discard,expect_retire,expect_recover_ready,expect_recovered,expect_error,expect_qready,expect_accepted,expect_busy,expect_response_valid,expect_response_slot,expect_response_port,expect_response_epoch,expect_response_tag,expect_response_read,expect_response_num,expect_response_last,expect_response_offset,expect_response_status,expect_response_data,expect_done_valid,expect_done_slot,expect_done_epoch,expect_generator_error);
if(rc!=58)$fatal(1,"parse");#1;
if({isolated,forward,epoch,count,tr,cr,discard,retire,recover_ready,recovered,error,qready,accepted,busy,response_valid,response_slot,response_port,response_epoch,response_tag,response_read,response_num,response_last,response_offset,response_status,response_data,done_valid,done_slot,done_epoch,generator_error}!=={expect_isolated,expect_forward,expect_epoch,expect_count,expect_tr,expect_cr,expect_discard,expect_retire,expect_recover_ready,expect_recovered,expect_error,expect_qready,expect_accepted,expect_busy,expect_response_valid,expect_response_slot,expect_response_port,expect_response_epoch,expect_response_tag,expect_response_read,expect_response_num,expect_response_last,expect_response_offset,expect_response_status,expect_response_data,expect_done_valid,expect_done_slot,expect_done_epoch,expect_generator_error})$fatal(1,"DUMMY_CHECK row=%0d count=%h/%h valid=%h/%h done=%h/%h tag=%h/%h offset=%h/%h",n,count,expect_count,response_valid,expect_response_valid,done_valid,expect_done_valid,response_tag,expect_response_tag,response_offset,expect_response_offset);
@(posedge clk);#1;end
$display("DUMMY_PASS unit=%0d ports=%0d cap=%0d switch=%0d rows=%0d",UNIT,P,C,SW,rows);$finish;
end
endmodule
