module kdlink_reliable_nic8 #( // Integrate the 16-bank NIC with eight canonical bonded endpoints.
    parameter integer NUM_RELIABLE_PLANES = 8, // Select instantiated planes for scalable verification.
    parameter [15:0] INITIAL_CREDITS = 16'd64, // Set the advertised receive capacity per VC.
    parameter integer REPLAY_SLOT_BITS = 9, // Set each logical-slice replay table size.
    parameter [15:0] REPLAY_TIMEOUT_CYCLES = 16'd4096, // Set the acknowledgement timeout.
    parameter integer KEEPALIVE_CYCLES = 1024, // Set the reverse heartbeat period.
    parameter integer LINK_TIMEOUT_CYCLES = 8192 // Set the peer timeout period.
) ( // Begin the reliable NIC port list.
    input wire core_clk_i, // Clock descriptor tensor and commit state.
    input wire core_rst_n_i, // Apply the active-low core reset.
    input wire phy_clk_i, // Clock reliable link and physical mapping state.
    input wire phy_rst_n_i, // Apply the active-low PHY reset.
    input wire [4:0] local_node_i, // Identify this NPU node.
    input wire [4:0] peer_node_i, // Identify the peer node for every enabled plane.
    input wire [7:0] link_epoch_i, // Apply the system-owned link epoch.
    input wire [7:0] link_enable_i, // Enable autonomous management independently per plane.
    input wire [15:0] configured_slice_mask_i, // Configure two physical slices per plane.
    input wire [15:0] slice_fault_i, // Remove failed physical slices per plane.
    input wire start_i, // Submit one NIC operation descriptor.
    output wire start_ready_o, // Report descriptor admission.
    input wire [511:0] descriptor_i, // Carry the canonical descriptor.
    input wire phase_i, // Select the collective phase encoded into headers.
    input wire finish_i, // Release the active NIC descriptor.
    output wire active_o, // Report an active NIC operation.
    output wire descriptor_error_o, // Report invalid descriptor fields.
    input wire [15:0] source_valid_i, // Qualify the 16 tensor source banks.
    output wire [15:0] source_ready_o, // Return source-bank admission.
    input wire [8191:0] source_data_i, // Carry 16 independent 512-bit payloads.
    input wire [111:0] source_bytes_i, // Carry valid-byte counts per source bank.
    input wire [15:0] source_eop_i, // Mark packet completion per source bank.
    input wire [79:0] source_dst_i, // Carry direct-operation destinations.
    output wire [15:0] result_valid_o, // Qualify exact-once committed result banks.
    input wire [15:0] result_ready_i, // Accept result banks independently.
    output wire [1535:0] result_header_o, // Return committed headers.
    output wire [8191:0] result_data_o, // Return committed payloads.
    output wire [111:0] result_bytes_o, // Return committed valid-byte counts.
    output wire [15:0] phy_forward_tx_valid_o, // Drive 16 physical forward slices.
    output wire [10239:0] phy_forward_tx_flit_o, // Drive 16 canonical 640-bit flits.
    input wire [15:0] phy_forward_rx_valid_i, // Receive 16 physical forward slices.
    input wire [10239:0] phy_forward_rx_flit_i, // Receive 16 canonical 640-bit flits.
    output wire [15:0] phy_reverse_tx_valid_o, // Drive 16 physical reverse slices.
    output wire [2047:0] phy_reverse_tx_word_o, // Drive 16 canonical 128-bit reverse words.
    input wire [15:0] phy_reverse_rx_valid_i, // Receive 16 physical reverse slices.
    input wire [2047:0] phy_reverse_rx_word_i, // Receive 16 canonical 128-bit reverse words.
    output wire [15:0] logical_link_up_o, // Report two logical links per plane.
    output wire [15:0] active_slice_mask_o, // Report healthy physical slices.
    output wire [7:0] epoch_recovery_required_o, // Request epoch recovery per bonded plane.
    output wire [7:0] reliability_error_o, // Report endpoint reliability errors per plane.
    output wire [7:0] mapping_error_o // Report bonded mapping errors per plane.
); // End the reliable NIC port list.
    wire [15:0] nic_link_tx_valid; // Carry NIC traffic into reliable endpoints.
    wire [15:0] nic_link_tx_ready; // Return reliable endpoint admission to the NIC.
    wire [1535:0] nic_link_tx_header; // Carry NIC-generated headers.
    wire [8191:0] nic_link_tx_data; // Carry NIC-generated payloads.
    wire [111:0] nic_link_tx_bytes; // Carry NIC-generated byte counts.
    wire [15:0] nic_link_rx_valid; // Carry committed endpoint traffic into the NIC.
    wire [15:0] nic_link_rx_ready; // Return NIC result-bank admission.
    wire [1535:0] nic_link_rx_header; // Carry committed headers into the NIC.
    wire [8191:0] nic_link_rx_data; // Carry committed payloads into the NIC.
    wire [111:0] nic_link_rx_bytes; // Carry committed byte counts into the NIC.
    wire [15:0] commit_last_unused; // Observe packet completion without exporting it.
    wire [15:0] source_stall_unused; // Observe NIC source stalls locally.
    wire [15:0] result_stall_unused; // Observe NIC result stalls locally.

    kdlink_nic8 u_nic ( // Instantiate the descriptor-driven 16-bank NIC.
        .clk_i(core_clk_i), .rst_n_i(core_rst_n_i), // Connect the core clock domain.
        .start_i(start_i), .start_ready_o(start_ready_o), .descriptor_i(descriptor_i), // Connect descriptor issue.
        .phase_i(phase_i), .link_epoch_i(link_epoch_i), .finish_i(finish_i), // Connect operation controls.
        .active_o(active_o), .descriptor_error_o(descriptor_error_o), // Export operation state.
        .source_valid_i(source_valid_i), .source_ready_o(source_ready_o), // Connect tensor source handshakes.
        .source_data_i(source_data_i), .source_bytes_i(source_bytes_i), // Connect tensor source payloads.
        .source_eop_i(source_eop_i), .source_dst_i(source_dst_i), // Connect packet and route metadata.
        .link_tx_valid_o(nic_link_tx_valid), .link_tx_ready_i(nic_link_tx_ready), // Connect reliable TX admission.
        .link_tx_header_o(nic_link_tx_header), .link_tx_data_o(nic_link_tx_data), // Connect reliable TX data.
        .link_tx_bytes_o(nic_link_tx_bytes), .link_rx_valid_i(nic_link_rx_valid), // Connect reliable RX valid.
        .link_rx_ready_o(nic_link_rx_ready), .link_rx_header_i(nic_link_rx_header), // Connect reliable RX headers.
        .link_rx_data_i(nic_link_rx_data), .link_rx_bytes_i(nic_link_rx_bytes), // Connect reliable RX data.
        .result_valid_o(result_valid_o), .result_ready_i(result_ready_i), // Connect tensor result handshakes.
        .result_header_o(result_header_o), .result_data_o(result_data_o), // Export tensor result data.
        .result_bytes_o(result_bytes_o), .source_stall_o(source_stall_unused), // Export result metadata.
        .result_stall_o(result_stall_unused) // Observe result stalls locally.
    ); // Complete the NIC instance.

    genvar plane_index; // Declare the bonded-plane generate index.
    generate // Build reliable endpoints for enabled planes and safe ties for omitted verification planes.
        for (plane_index = 0; plane_index < 8; plane_index = plane_index + 1) begin : g_plane // Build one plane boundary.
            if (plane_index < NUM_RELIABLE_PLANES) begin : g_reliable // Instantiate a canonical bonded endpoint.
                wire [19:0] replay_occupancy_unused; // Observe both logical replay occupancies locally.
                wire degraded_unused; // Observe degraded mode locally.
                wire link_down_unused; // Observe complete plane loss locally.
                kdlink_reliable_bonded_endpoint #( // Configure the canonical endpoint pair.
                    .INITIAL_CREDITS(INITIAL_CREDITS), // Apply receive capacity.
                    .REPLAY_SLOT_BITS(REPLAY_SLOT_BITS), // Apply replay-window size.
                    .REPLAY_TIMEOUT_CYCLES(REPLAY_TIMEOUT_CYCLES), // Apply timeout recovery.
                    .KEEPALIVE_CYCLES(KEEPALIVE_CYCLES), // Apply heartbeat interval.
                    .LINK_TIMEOUT_CYCLES(LINK_TIMEOUT_CYCLES) // Apply peer timeout.
                ) u_bonded_endpoint ( // Instantiate one reliable plane.
                    .core_clk_i(core_clk_i), .core_rst_n_i(core_rst_n_i), // Connect core clocking.
                    .phy_clk_i(phy_clk_i), .phy_rst_n_i(phy_rst_n_i), // Connect PHY clocking.
                    .local_node_i(local_node_i), .peer_node_i(peer_node_i), // Connect endpoint identities.
                    .link_epoch_i(link_epoch_i), .link_enable_i(link_enable_i[plane_index]), // Connect management controls.
                    .configured_slice_mask_i(configured_slice_mask_i[plane_index*2 +: 2]), // Connect physical configuration.
                    .slice_fault_i(slice_fault_i[plane_index*2 +: 2]), // Connect physical fault state.
                    .tx_valid_i(nic_link_tx_valid[plane_index*2 +: 2]), // Connect NIC TX valid.
                    .tx_ready_o(nic_link_tx_ready[plane_index*2 +: 2]), // Return NIC TX admission.
                    .tx_header_i(nic_link_tx_header[plane_index*192 +: 192]), // Connect two NIC headers.
                    .tx_payload_i(nic_link_tx_data[plane_index*1024 +: 1024]), // Connect two NIC payloads.
                    .tx_payload_bytes_i(nic_link_tx_bytes[plane_index*14 +: 14]), // Connect byte counts.
                    .rx_commit_valid_o(nic_link_rx_valid[plane_index*2 +: 2]), // Return committed valid.
                    .rx_commit_ready_i(nic_link_rx_ready[plane_index*2 +: 2]), // Accept committed data.
                    .rx_commit_header_o(nic_link_rx_header[plane_index*192 +: 192]), // Return committed headers.
                    .rx_commit_payload_o(nic_link_rx_data[plane_index*1024 +: 1024]), // Return committed payloads.
                    .rx_commit_payload_bytes_o(nic_link_rx_bytes[plane_index*14 +: 14]), // Return byte counts.
                    .rx_commit_last_o(commit_last_unused[plane_index*2 +: 2]), // Observe packet completion.
                    .phy_forward_tx_valid_o(phy_forward_tx_valid_o[plane_index*2 +: 2]), // Drive forward slices.
                    .phy_forward_tx_flit_o(phy_forward_tx_flit_o[plane_index*1280 +: 1280]), // Drive forward flits.
                    .phy_forward_rx_valid_i(phy_forward_rx_valid_i[plane_index*2 +: 2]), // Receive forward slices.
                    .phy_forward_rx_flit_i(phy_forward_rx_flit_i[plane_index*1280 +: 1280]), // Receive forward flits.
                    .phy_reverse_tx_valid_o(phy_reverse_tx_valid_o[plane_index*2 +: 2]), // Drive reverse slices.
                    .phy_reverse_tx_word_o(phy_reverse_tx_word_o[plane_index*256 +: 256]), // Drive reverse words.
                    .phy_reverse_rx_valid_i(phy_reverse_rx_valid_i[plane_index*2 +: 2]), // Receive reverse slices.
                    .phy_reverse_rx_word_i(phy_reverse_rx_word_i[plane_index*256 +: 256]), // Receive reverse words.
                    .logical_link_up_o(logical_link_up_o[plane_index*2 +: 2]), // Export logical link state.
                    .active_slice_mask_o(active_slice_mask_o[plane_index*2 +: 2]), // Export active slices.
                    .degraded_o(degraded_unused), .link_down_o(link_down_unused), // Observe aggregate slice state.
                    .epoch_recovery_required_o(epoch_recovery_required_o[plane_index]), // Export epoch request.
                    .mapping_error_o(mapping_error_o[plane_index]), // Export mapping errors.
                    .reliability_error_o(reliability_error_o[plane_index]), // Export reliability errors.
                    .replay_occupancy_o(replay_occupancy_unused) // Observe replay occupancy.
                ); // Complete one canonical reliable plane.
            end else begin : g_disabled // Tie omitted verification planes to inactive values.
                assign nic_link_tx_ready[plane_index*2 +: 2] = 2'b00; // Backpressure disabled NIC banks.
                assign nic_link_rx_valid[plane_index*2 +: 2] = 2'b00; // Suppress disabled receive banks.
                assign nic_link_rx_header[plane_index*192 +: 192] = 192'd0; // Clear disabled headers.
                assign nic_link_rx_data[plane_index*1024 +: 1024] = 1024'd0; // Clear disabled payloads.
                assign nic_link_rx_bytes[plane_index*14 +: 14] = 14'd0; // Clear disabled byte counts.
                assign commit_last_unused[plane_index*2 +: 2] = 2'b00; // Clear disabled packet completion.
                assign phy_forward_tx_valid_o[plane_index*2 +: 2] = 2'b00; // Disable forward outputs.
                assign phy_forward_tx_flit_o[plane_index*1280 +: 1280] = 1280'd0; // Clear forward data.
                assign phy_reverse_tx_valid_o[plane_index*2 +: 2] = 2'b00; // Disable reverse outputs.
                assign phy_reverse_tx_word_o[plane_index*256 +: 256] = 256'd0; // Clear reverse data.
                assign logical_link_up_o[plane_index*2 +: 2] = 2'b00; // Report disabled logical links down.
                assign active_slice_mask_o[plane_index*2 +: 2] = 2'b00; // Report no active slices.
                assign epoch_recovery_required_o[plane_index] = 1'b0; // Clear disabled epoch requests.
                assign reliability_error_o[plane_index] = 1'b0; // Clear disabled reliability status.
                assign mapping_error_o[plane_index] = 1'b0; // Clear disabled mapping status.
            end // Complete disabled-plane ties.
        end // Complete one plane generate body.
    endgenerate // Complete all eight plane boundaries.
endmodule // Complete the canonical reliable NIC8 integration.
