`ifndef KDLINK_DEFS_VH // 防止 KDLink 常量被重复包含
`define KDLINK_DEFS_VH // 声明 KDLink 常量保护宏
`define KDL_SCHEMA_VERSION 2 // 固定协议 schema 版本
`define KDL_NUM_NODES 32 // 固定 KDLink 架构参数
`define KDL_NUM_PLANES 8 // 固定 KDLink 架构参数
`define KDL_SLICES_PER_PORT 2 // 固定 KDLink 架构参数
`define KDL_NUM_VC 8 // 固定 KDLink 架构参数
`define KDL_NUM_CONTEXTS 16 // 固定 KDLink 架构参数
`define KDL_VC_DEPTH 64 // 固定 KDLink 架构参数
`define KDL_PAYLOAD_WIDTH 512 // 固定 KDLink 架构参数
`define KDL_HEADER_WIDTH 128 // 固定 KDLink 架构参数
`define KDL_FLIT_WIDTH 640 // 固定 KDLink 架构参数
`define KDL_REVERSE_WIDTH 128 // 固定 KDLink 架构参数
`define KDL_DESCRIPTOR_WIDTH 512 // 固定 KDLink 架构参数
`define KDL_MAX_PACKET_FLITS 16 // 固定 KDLink 架构参数
`define KDL_PACKET_SEQUENCE_MODULUS 4096 // 固定 KDLink 架构参数
`define KDL_SLICE_CLOCK_HZ 1000000000 // 固定 KDLink 架构参数
`define KDL_PCS_BLOCK_DATA_WIDTH 64 // 固定 KDLink 架构参数
`define KDL_PCS_BLOCK_WIDTH 66 // 固定 KDLink 架构参数
`define KDL_PCS_BLOCKS_PER_FLIT 10 // 固定 KDLink 架构参数
`define KDL_OPCODE_REDUCE_SCATTER 0 // 固定 KDLink 编码
`define KDL_OPCODE_ALL_GATHER 1 // 固定 KDLink 编码
`define KDL_OPCODE_ALL_REDUCE 2 // 固定 KDLink 编码
`define KDL_OPCODE_ALL_TO_ALL 3 // 固定 KDLink 编码
`define KDL_OPCODE_ALL_TO_ALL_V 4 // 固定 KDLink 编码
`define KDL_OPCODE_POINT_TO_POINT 5 // 固定 KDLink 编码
`define KDL_DTYPE_INT32 0 // 固定 KDLink 编码
`define KDL_DTYPE_FP32 1 // 固定 KDLink 编码
`define KDL_DTYPE_FP16 2 // 固定 KDLink 编码
`define KDL_DTYPE_BF16 3 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_DATA 0 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_COLL_SETUP 1 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_COLL_COMMIT 2 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_COLL_ABORT 3 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_KEEPALIVE 4 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_LINK_INIT 5 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_LINK_STATE 6 // 固定 KDLink 编码
`define KDL_MESSAGE_TYPE_FAULT 7 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_CREDIT 0 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_ACK 1 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_NACK 2 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_LINK_RESET 3 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_INIT_ACK 4 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_KEEPALIVE_ACK 5 // 固定 KDLink 编码
`define KDL_REVERSE_TYPE_LANE_STATUS 6 // 固定 KDLink 编码
`define KDL_VC_ROLE_ESCAPE 0 // 固定 KDLink 编码
`define KDL_VC_ROLE_LATENCY 1 // 固定 KDLink 编码
`define KDL_VC_ROLE_COLLECTIVE 2 // 固定 KDLink 编码
`define KDL_VC_ROLE_ALL_TO_ALL_V 3 // 固定 KDLink 编码
`define KDL_VC_ROLE_POINT_TO_POINT 4 // 固定 KDLink 编码
`define KDL_VC_ROLE_CONTROL 5 // 固定 KDLink 编码
`define KDL_VC_ROLE_REPLAY 6 // 固定 KDLink 编码
`define KDL_VC_ROLE_MANAGEMENT 7 // 固定 KDLink 编码
`define KDL_ALGORITHM_AUTO 0 // 固定 KDLink 编码
`define KDL_ALGORITHM_RING 1 // 固定 KDLink 编码
`define KDL_ALGORITHM_TREE 2 // 固定 KDLink 编码
`define KDL_ALGORITHM_DIRECT 3 // 固定 KDLink 编码
`define KDL_DESCRIPTOR_OPCODE_LSB 0 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_OPCODE_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_DTYPE_LSB 3 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_DTYPE_WIDTH 2 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_LOCAL_NODE_LSB 5 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_LOCAL_NODE_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_NUM_NODES_LSB 10 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_NUM_NODES_WIDTH 6 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_IN_PLACE_LSB 16 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_IN_PLACE_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_IRQ_ON_COMPLETION_LSB 17 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_IRQ_ON_COMPLETION_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_ALGORITHM_LSB 18 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_ALGORITHM_WIDTH 2 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_STRICT_ORDER_LSB 20 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_STRICT_ORDER_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_DESCRIPTOR_VERSION_LSB 21 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_DESCRIPTOR_VERSION_WIDTH 4 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_COLLECTIVE_ID_LSB 25 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_COLLECTIVE_ID_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_TIMEOUT_QUANTA_LSB 37 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_TIMEOUT_QUANTA_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_PLANE_MASK_LSB 49 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_PLANE_MASK_WIDTH 8 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_SLICE_MASK_LSB 57 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_SLICE_MASK_WIDTH 2 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_PRIORITY_LSB 59 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_PRIORITY_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_RESERVED0_LSB 62 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_RESERVED0_WIDTH 2 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_SRC_ADDR_LSB 64 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_SRC_ADDR_WIDTH 64 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_DST_ADDR_LSB 128 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_DST_ADDR_WIDTH 64 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_LENGTH_BYTES_LSB 192 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_LENGTH_BYTES_WIDTH 32 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_COUNTS_ADDR_LSB 224 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_COUNTS_ADDR_WIDTH 64 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_OFFSETS_ADDR_LSB 288 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_OFFSETS_ADDR_WIDTH 64 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_PEER_MASK_LSB 352 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_PEER_MASK_WIDTH 32 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_USER_TAG_LSB 384 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_USER_TAG_WIDTH 32 // 固定 KDLink 字段位宽
`define KDL_DESCRIPTOR_RESERVED1_LSB 416 // 固定 KDLink 字段最低位
`define KDL_DESCRIPTOR_RESERVED1_WIDTH 96 // 固定 KDLink 字段位宽
`define KDL_HEADER_VERSION_LSB 0 // 固定 KDLink 字段最低位
`define KDL_HEADER_VERSION_WIDTH 4 // 固定 KDLink 字段位宽
`define KDL_HEADER_MESSAGE_TYPE_LSB 4 // 固定 KDLink 字段最低位
`define KDL_HEADER_MESSAGE_TYPE_WIDTH 4 // 固定 KDLink 字段位宽
`define KDL_HEADER_OPCODE_LSB 8 // 固定 KDLink 字段最低位
`define KDL_HEADER_OPCODE_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_HEADER_DTYPE_LSB 11 // 固定 KDLink 字段最低位
`define KDL_HEADER_DTYPE_WIDTH 2 // 固定 KDLink 字段位宽
`define KDL_HEADER_VC_LSB 13 // 固定 KDLink 字段最低位
`define KDL_HEADER_VC_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_HEADER_PHASE_LSB 16 // 固定 KDLink 字段最低位
`define KDL_HEADER_PHASE_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_HEADER_SOP_LSB 17 // 固定 KDLink 字段最低位
`define KDL_HEADER_SOP_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_HEADER_EOP_LSB 18 // 固定 KDLink 字段最低位
`define KDL_HEADER_EOP_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_HEADER_RETRY_LSB 19 // 固定 KDLink 字段最低位
`define KDL_HEADER_RETRY_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_HEADER_SRC_NODE_LSB 20 // 固定 KDLink 字段最低位
`define KDL_HEADER_SRC_NODE_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_HEADER_DST_NODE_LSB 25 // 固定 KDLink 字段最低位
`define KDL_HEADER_DST_NODE_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_HEADER_PLANE_ID_LSB 30 // 固定 KDLink 字段最低位
`define KDL_HEADER_PLANE_ID_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_HEADER_HOP_LIMIT_LSB 33 // 固定 KDLink 字段最低位
`define KDL_HEADER_HOP_LIMIT_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_HEADER_LINK_EPOCH_LSB 38 // 固定 KDLink 字段最低位
`define KDL_HEADER_LINK_EPOCH_WIDTH 8 // 固定 KDLink 字段位宽
`define KDL_HEADER_COLLECTIVE_ID_LSB 46 // 固定 KDLink 字段最低位
`define KDL_HEADER_COLLECTIVE_ID_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_HEADER_CHUNK_ID_LSB 58 // 固定 KDLink 字段最低位
`define KDL_HEADER_CHUNK_ID_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_HEADER_PACKET_SEQ_LSB 70 // 固定 KDLink 字段最低位
`define KDL_HEADER_PACKET_SEQ_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_HEADER_FLIT_SEQ_LSB 82 // 固定 KDLink 字段最低位
`define KDL_HEADER_FLIT_SEQ_WIDTH 6 // 固定 KDLink 字段位宽
`define KDL_HEADER_PAYLOAD_BYTES_LSB 88 // 固定 KDLink 字段最低位
`define KDL_HEADER_PAYLOAD_BYTES_WIDTH 7 // 固定 KDLink 字段位宽
`define KDL_HEADER_RESERVED_LSB 95 // 固定 KDLink 字段最低位
`define KDL_HEADER_RESERVED_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_HEADER_CRC32_LSB 96 // 固定 KDLink 字段最低位
`define KDL_HEADER_CRC32_WIDTH 32 // 固定 KDLink 字段位宽
`define KDL_REVERSE_VERSION_LSB 0 // 固定 KDLink 字段最低位
`define KDL_REVERSE_VERSION_WIDTH 4 // 固定 KDLink 字段位宽
`define KDL_REVERSE_MESSAGE_TYPE_LSB 4 // 固定 KDLink 字段最低位
`define KDL_REVERSE_MESSAGE_TYPE_WIDTH 4 // 固定 KDLink 字段位宽
`define KDL_REVERSE_VC_LSB 8 // 固定 KDLink 字段最低位
`define KDL_REVERSE_VC_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_REVERSE_PLANE_ID_LSB 11 // 固定 KDLink 字段最低位
`define KDL_REVERSE_PLANE_ID_WIDTH 3 // 固定 KDLink 字段位宽
`define KDL_REVERSE_SLICE_ID_LSB 14 // 固定 KDLink 字段最低位
`define KDL_REVERSE_SLICE_ID_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_REVERSE_PHASE_LSB 15 // 固定 KDLink 字段最低位
`define KDL_REVERSE_PHASE_WIDTH 1 // 固定 KDLink 字段位宽
`define KDL_REVERSE_LINK_EPOCH_LSB 16 // 固定 KDLink 字段最低位
`define KDL_REVERSE_LINK_EPOCH_WIDTH 8 // 固定 KDLink 字段位宽
`define KDL_REVERSE_SRC_NODE_LSB 24 // 固定 KDLink 字段最低位
`define KDL_REVERSE_SRC_NODE_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_REVERSE_DST_NODE_LSB 29 // 固定 KDLink 字段最低位
`define KDL_REVERSE_DST_NODE_WIDTH 5 // 固定 KDLink 字段位宽
`define KDL_REVERSE_COLLECTIVE_ID_LSB 34 // 固定 KDLink 字段最低位
`define KDL_REVERSE_COLLECTIVE_ID_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_REVERSE_PACKET_SEQ_LSB 46 // 固定 KDLink 字段最低位
`define KDL_REVERSE_PACKET_SEQ_WIDTH 12 // 固定 KDLink 字段位宽
`define KDL_REVERSE_CREDIT_DELTA_LSB 58 // 固定 KDLink 字段最低位
`define KDL_REVERSE_CREDIT_DELTA_WIDTH 8 // 固定 KDLink 字段位宽
`define KDL_REVERSE_CREDIT_TOTAL_LSB 66 // 固定 KDLink 字段最低位
`define KDL_REVERSE_CREDIT_TOTAL_WIDTH 16 // 固定 KDLink 字段位宽
`define KDL_REVERSE_ACK_BITMAP_LSB 82 // 固定 KDLink 字段最低位
`define KDL_REVERSE_ACK_BITMAP_WIDTH 16 // 固定 KDLink 字段位宽
`define KDL_REVERSE_STATUS_LSB 98 // 固定 KDLink 字段最低位
`define KDL_REVERSE_STATUS_WIDTH 8 // 固定 KDLink 字段位宽
`define KDL_REVERSE_RESERVED_LSB 106 // 固定 KDLink 字段最低位
`define KDL_REVERSE_RESERVED_WIDTH 6 // 固定 KDLink 字段位宽
`define KDL_REVERSE_CRC16_LSB 112 // 固定 KDLink 字段最低位
`define KDL_REVERSE_CRC16_WIDTH 16 // 固定 KDLink 字段位宽
`endif // 结束 KDLink 常量保护宏
