`timescale 1ns/1ps
`default_nettype none
// Destination Group数组：每个Group保留独立Tile×bank并行面和独立物理容量账本，不执行跨Group merge。
module switch_destination_group_array #(
 parameter integer C_NUM_GROUPS=8,C_PLANES=32,C_TILES=4,C_BANK_LANES=8,
 parameter integer C_DATA_WIDTH=256,C_META_WIDTH=128,C_TILE_WIDTH=2,C_CLASS_WIDTH=2,C_VC_WIDTH=2,
 parameter integer C_COUNT_WIDTH=5,C_CORE_CONTEXT_WIDTH=5,C_PLANE_WIDTH=5,C_OWNER_WIDTH=6,C_RESOURCE_WIDTH=9,
 parameter integer C_EPOCH_WIDTH=4,C_GENERATION_WIDTH=8,C_SLOT_WIDTH=11,C_BANK_SLOT_WIDTH=2,
 parameter integer C_ACCOUNT_WIDTH=15,C_TOKEN_WIDTH=C_EPOCH_WIDTH+C_GENERATION_WIDTH+C_SLOT_WIDTH,
 parameter integer C_CREDIT_COUNT_WIDTH=3,C_DST_LOCALS=32,C_NUM_CLASSES=4,C_NUM_VC=4,C_CAPACITY=4,
 parameter integer C_LANES=C_TILES*C_BANK_LANES,parameter integer C_REQUESTERS=C_LANES+C_PLANES,
 parameter integer C_RESOURCES=C_TILES*C_DST_LOCALS*C_NUM_CLASSES,
 parameter integer C_ACCOUNTS=C_REQUESTERS*C_RESOURCES,parameter integer C_RELEASE_PORTS=C_TILES*C_DST_LOCALS
)(
 input wire i_clk,input wire i_rstn,input wire [C_EPOCH_WIDTH-1:0] i_epoch,
 input wire [C_NUM_GROUPS*C_LANES-1:0] i_local_valid,output wire [C_NUM_GROUPS*C_LANES-1:0] o_local_ready,
 input wire [C_NUM_GROUPS*C_LANES*C_DATA_WIDTH-1:0] i_local_data,
 input wire [C_NUM_GROUPS*C_LANES*C_META_WIDTH-1:0] i_local_meta,
 input wire [C_NUM_GROUPS*C_LANES*3-1:0] i_local_dst_group,
 input wire [C_NUM_GROUPS*C_LANES*C_TILE_WIDTH-1:0] i_local_dst_tile,
 input wire [C_NUM_GROUPS*C_LANES*5-1:0] i_local_dst_port,
 input wire [C_NUM_GROUPS*C_LANES*C_CLASS_WIDTH-1:0] i_local_class,
 input wire [C_NUM_GROUPS*C_LANES*C_VC_WIDTH-1:0] i_local_original_vc,
 input wire [C_NUM_GROUPS*C_LANES-1:0] i_local_pool,
 input wire [C_NUM_GROUPS*C_LANES*C_COUNT_WIDTH-1:0] i_local_packet_flits,
 input wire [C_NUM_GROUPS*C_LANES-1:0] i_local_sop,input wire [C_NUM_GROUPS*C_LANES-1:0] i_local_eop,
 input wire [C_NUM_GROUPS*C_PLANES-1:0] i_core_valid,output wire [C_NUM_GROUPS*C_PLANES-1:0] o_core_ready,
 input wire [C_NUM_GROUPS*C_PLANES*C_DATA_WIDTH-1:0] i_core_data,
 input wire [C_NUM_GROUPS*C_PLANES*C_META_WIDTH-1:0] i_core_meta,
 input wire [C_NUM_GROUPS*C_PLANES*3-1:0] i_core_dst_group,
 input wire [C_NUM_GROUPS*C_PLANES*C_TILE_WIDTH-1:0] i_core_dst_tile,
 input wire [C_NUM_GROUPS*C_PLANES*5-1:0] i_core_dst_port,
 input wire [C_NUM_GROUPS*C_PLANES*C_CLASS_WIDTH-1:0] i_core_class,
 input wire [C_NUM_GROUPS*C_PLANES*C_COUNT_WIDTH-1:0] i_core_packet_flits,
 input wire [C_NUM_GROUPS*C_PLANES*C_CORE_CONTEXT_WIDTH-1:0] i_core_context,
 input wire [C_NUM_GROUPS*C_PLANES*C_VC_WIDTH-1:0] i_core_original_vc,
 input wire [C_NUM_GROUPS*C_PLANES-1:0] i_core_pool,
 input wire [C_NUM_GROUPS*C_PLANES-1:0] i_core_sop,input wire [C_NUM_GROUPS*C_PLANES-1:0] i_core_eop,
 output wire [C_NUM_GROUPS*C_LANES-1:0] o_valid,input wire [C_NUM_GROUPS*C_LANES-1:0] i_ready,
 output wire [C_NUM_GROUPS*C_LANES*C_DATA_WIDTH-1:0] o_data,
 output wire [C_NUM_GROUPS*C_LANES*C_META_WIDTH-1:0] o_meta,
 output wire [C_NUM_GROUPS*C_LANES*3-1:0] o_dst_group,
 output wire [C_NUM_GROUPS*C_LANES*C_TILE_WIDTH-1:0] o_dst_tile,
 output wire [C_NUM_GROUPS*C_LANES*5-1:0] o_dst_port,
 output wire [C_NUM_GROUPS*C_LANES*C_CLASS_WIDTH-1:0] o_class,
 output wire [C_NUM_GROUPS*C_LANES*C_VC_WIDTH-1:0] o_original_vc,
 output wire [C_NUM_GROUPS*C_LANES-1:0] o_pool,
 output wire [C_NUM_GROUPS*C_LANES*C_ACCOUNT_WIDTH-1:0] o_account,
 output wire [C_NUM_GROUPS*C_LANES*C_TOKEN_WIDTH-1:0] o_token,
 output wire [C_NUM_GROUPS*C_LANES-1:0] o_sop,output wire [C_NUM_GROUPS*C_LANES-1:0] o_eop,
 output wire [C_NUM_GROUPS*C_PLANES-1:0] o_core_registered_eligibility,
 output wire [C_NUM_GROUPS*C_PLANES*C_TILE_WIDTH-1:0] o_core_eligibility_dst_tile,
 output wire [C_NUM_GROUPS*C_PLANES*5-1:0] o_core_eligibility_dst_port,
 output wire [C_NUM_GROUPS*C_PLANES*C_CLASS_WIDTH-1:0] o_core_eligibility_class,
 output wire [C_NUM_GROUPS*C_EPOCH_WIDTH-1:0] o_core_eligibility_epoch,
 input wire [C_NUM_GROUPS*C_RELEASE_PORTS-1:0] i_release_valid,
 output wire [C_NUM_GROUPS*C_RELEASE_PORTS-1:0] o_release_ready,
 input wire [C_NUM_GROUPS*C_RELEASE_PORTS*C_TOKEN_WIDTH-1:0] i_release_token,
 output wire [C_NUM_GROUPS*C_RESOURCES*C_CREDIT_COUNT_WIDTH-1:0] o_free,
 output wire [C_NUM_GROUPS*C_RESOURCES*C_CREDIT_COUNT_WIDTH-1:0] o_effective_free,
 output wire [C_NUM_GROUPS*C_ACCOUNTS*C_CREDIT_COUNT_WIDTH-1:0] o_issued,
 output wire [C_NUM_GROUPS*C_ACCOUNTS*C_CREDIT_COUNT_WIDTH-1:0] o_occupied,
 output wire [C_NUM_GROUPS-1:0] o_group_quiescent,output wire [C_NUM_GROUPS-1:0] o_group_error,
 output wire [C_NUM_GROUPS-1:0] o_return_malformed_event_level,
 output wire [C_NUM_GROUPS-1:0] o_return_duplicate_event_level,
 output wire [C_NUM_GROUPS-1:0] o_return_stale_event_level,
 output wire [C_NUM_GROUPS-1:0] o_return_wrong_port_event_level
);
 genvar group_index;
 generate for(group_index=0;group_index<C_NUM_GROUPS;group_index=group_index+1)begin:g_destination_group
  switch_destination_group_credit_fabric #(.C_PLANES(C_PLANES),.C_TILES(C_TILES),.C_BANK_LANES(C_BANK_LANES),
   .C_DATA_WIDTH(C_DATA_WIDTH),.C_META_WIDTH(C_META_WIDTH),.C_TILE_WIDTH(C_TILE_WIDTH),.C_CLASS_WIDTH(C_CLASS_WIDTH),
   .C_VC_WIDTH(C_VC_WIDTH),.C_COUNT_WIDTH(C_COUNT_WIDTH),.C_CORE_CONTEXT_WIDTH(C_CORE_CONTEXT_WIDTH),
   .C_PLANE_WIDTH(C_PLANE_WIDTH),.C_OWNER_WIDTH(C_OWNER_WIDTH),.C_RESOURCE_WIDTH(C_RESOURCE_WIDTH),
   .C_EPOCH_WIDTH(C_EPOCH_WIDTH),.C_GENERATION_WIDTH(C_GENERATION_WIDTH),.C_SLOT_WIDTH(C_SLOT_WIDTH),
   .C_BANK_SLOT_WIDTH(C_BANK_SLOT_WIDTH),.C_ACCOUNT_WIDTH(C_ACCOUNT_WIDTH),.C_TOKEN_WIDTH(C_TOKEN_WIDTH),
   .C_CREDIT_COUNT_WIDTH(C_CREDIT_COUNT_WIDTH),.C_DST_LOCALS(C_DST_LOCALS),.C_NUM_CLASSES(C_NUM_CLASSES),
   .C_NUM_VC(C_NUM_VC),.C_CAPACITY(C_CAPACITY),.C_NUM_GROUPS(C_NUM_GROUPS),.C_GROUP_ID(group_index),
   .C_LANES(C_LANES),.C_REQUESTERS(C_REQUESTERS),.C_RESOURCES(C_RESOURCES),.C_ACCOUNTS(C_ACCOUNTS),
   .C_RELEASE_PORTS(C_RELEASE_PORTS))u_group(.i_clk(i_clk),.i_rstn(i_rstn),.i_epoch(i_epoch),
   .i_local_valid(i_local_valid[group_index*C_LANES+:C_LANES]),.o_local_ready(o_local_ready[group_index*C_LANES+:C_LANES]),
   .i_local_data(i_local_data[group_index*C_LANES*C_DATA_WIDTH+:C_LANES*C_DATA_WIDTH]),
   .i_local_meta(i_local_meta[group_index*C_LANES*C_META_WIDTH+:C_LANES*C_META_WIDTH]),
   .i_local_dst_group(i_local_dst_group[group_index*C_LANES*3+:C_LANES*3]),
   .i_local_dst_tile(i_local_dst_tile[group_index*C_LANES*C_TILE_WIDTH+:C_LANES*C_TILE_WIDTH]),
   .i_local_dst_port(i_local_dst_port[group_index*C_LANES*5+:C_LANES*5]),
   .i_local_class(i_local_class[group_index*C_LANES*C_CLASS_WIDTH+:C_LANES*C_CLASS_WIDTH]),
   .i_local_original_vc(i_local_original_vc[group_index*C_LANES*C_VC_WIDTH+:C_LANES*C_VC_WIDTH]),
   .i_local_pool(i_local_pool[group_index*C_LANES+:C_LANES]),
   .i_local_packet_flits(i_local_packet_flits[group_index*C_LANES*C_COUNT_WIDTH+:C_LANES*C_COUNT_WIDTH]),
   .i_local_sop(i_local_sop[group_index*C_LANES+:C_LANES]),
   .i_local_eop(i_local_eop[group_index*C_LANES+:C_LANES]),
   .i_core_valid(i_core_valid[group_index*C_PLANES+:C_PLANES]),.o_core_ready(o_core_ready[group_index*C_PLANES+:C_PLANES]),
   .i_core_data(i_core_data[group_index*C_PLANES*C_DATA_WIDTH+:C_PLANES*C_DATA_WIDTH]),
   .i_core_meta(i_core_meta[group_index*C_PLANES*C_META_WIDTH+:C_PLANES*C_META_WIDTH]),
   .i_core_dst_group(i_core_dst_group[group_index*C_PLANES*3+:C_PLANES*3]),
   .i_core_dst_tile(i_core_dst_tile[group_index*C_PLANES*C_TILE_WIDTH+:C_PLANES*C_TILE_WIDTH]),
   .i_core_dst_port(i_core_dst_port[group_index*C_PLANES*5+:C_PLANES*5]),
   .i_core_class(i_core_class[group_index*C_PLANES*C_CLASS_WIDTH+:C_PLANES*C_CLASS_WIDTH]),
   .i_core_packet_flits(i_core_packet_flits[group_index*C_PLANES*C_COUNT_WIDTH+:C_PLANES*C_COUNT_WIDTH]),
   .i_core_context(i_core_context[group_index*C_PLANES*C_CORE_CONTEXT_WIDTH+:C_PLANES*C_CORE_CONTEXT_WIDTH]),
   .i_core_original_vc(i_core_original_vc[group_index*C_PLANES*C_VC_WIDTH+:C_PLANES*C_VC_WIDTH]),
   .i_core_pool(i_core_pool[group_index*C_PLANES+:C_PLANES]),.i_core_sop(i_core_sop[group_index*C_PLANES+:C_PLANES]),
   .i_core_eop(i_core_eop[group_index*C_PLANES+:C_PLANES]),
   .o_core_registered_eligibility(o_core_registered_eligibility[group_index*C_PLANES+:C_PLANES]),
   .o_core_eligibility_dst_tile(o_core_eligibility_dst_tile[group_index*C_PLANES*C_TILE_WIDTH+:C_PLANES*C_TILE_WIDTH]),
   .o_core_eligibility_dst_port(o_core_eligibility_dst_port[group_index*C_PLANES*5+:C_PLANES*5]),
   .o_core_eligibility_class(o_core_eligibility_class[group_index*C_PLANES*C_CLASS_WIDTH+:C_PLANES*C_CLASS_WIDTH]),
   .o_core_eligibility_epoch(o_core_eligibility_epoch[group_index*C_EPOCH_WIDTH+:C_EPOCH_WIDTH]),
   .o_valid(o_valid[group_index*C_LANES+:C_LANES]),.i_ready(i_ready[group_index*C_LANES+:C_LANES]),
   .o_data(o_data[group_index*C_LANES*C_DATA_WIDTH+:C_LANES*C_DATA_WIDTH]),
   .o_meta(o_meta[group_index*C_LANES*C_META_WIDTH+:C_LANES*C_META_WIDTH]),
   .o_dst_group(o_dst_group[group_index*C_LANES*3+:C_LANES*3]),
   .o_dst_tile(o_dst_tile[group_index*C_LANES*C_TILE_WIDTH+:C_LANES*C_TILE_WIDTH]),
   .o_dst_port(o_dst_port[group_index*C_LANES*5+:C_LANES*5]),
   .o_class(o_class[group_index*C_LANES*C_CLASS_WIDTH+:C_LANES*C_CLASS_WIDTH]),
   .o_original_vc(o_original_vc[group_index*C_LANES*C_VC_WIDTH+:C_LANES*C_VC_WIDTH]),
   .o_pool(o_pool[group_index*C_LANES+:C_LANES]),
   .o_account(o_account[group_index*C_LANES*C_ACCOUNT_WIDTH+:C_LANES*C_ACCOUNT_WIDTH]),
   .o_token(o_token[group_index*C_LANES*C_TOKEN_WIDTH+:C_LANES*C_TOKEN_WIDTH]),
   .o_sop(o_sop[group_index*C_LANES+:C_LANES]),.o_eop(o_eop[group_index*C_LANES+:C_LANES]),
   .i_release_valid(i_release_valid[group_index*C_RELEASE_PORTS+:C_RELEASE_PORTS]),
   .o_release_ready(o_release_ready[group_index*C_RELEASE_PORTS+:C_RELEASE_PORTS]),
   .i_release_token(i_release_token[group_index*C_RELEASE_PORTS*C_TOKEN_WIDTH+:C_RELEASE_PORTS*C_TOKEN_WIDTH]),
   .o_free(o_free[group_index*C_RESOURCES*C_CREDIT_COUNT_WIDTH+:C_RESOURCES*C_CREDIT_COUNT_WIDTH]),
   .o_effective_free(o_effective_free[group_index*C_RESOURCES*C_CREDIT_COUNT_WIDTH+:C_RESOURCES*C_CREDIT_COUNT_WIDTH]),
   .o_issued(o_issued[group_index*C_ACCOUNTS*C_CREDIT_COUNT_WIDTH+:C_ACCOUNTS*C_CREDIT_COUNT_WIDTH]),
   .o_occupied(o_occupied[group_index*C_ACCOUNTS*C_CREDIT_COUNT_WIDTH+:C_ACCOUNTS*C_CREDIT_COUNT_WIDTH]),
   .o_quiescent(o_group_quiescent[group_index]),.o_error(o_group_error[group_index]),
   .o_return_malformed_event_level(o_return_malformed_event_level[group_index]),
   .o_return_duplicate_event_level(o_return_duplicate_event_level[group_index]),
   .o_return_stale_event_level(o_return_stale_event_level[group_index]),
   .o_return_wrong_port_event_level(o_return_wrong_port_event_level[group_index]));
 end endgenerate
endmodule
`default_nettype wire
