`timescale 1ns/1ps
`default_nettype none
// 可选只读计量包装层。所有业务端口逐名直连production managed top；
// 计量器只消费其显式observation tap，不能生成或修改业务ready/valid。
module ualink_switch_full_ip_managed_instrumented_top #(
 parameter integer C_NUM_STATIONS=8,parameter integer C_NUM_GROUPS=1,
 parameter integer C_TILES_PER_GROUP=1,parameter integer C_INGRESS_PER_TILE=32,
 parameter integer C_BANKS_PER_TILE=8,parameter integer C_NUM_PLANES=1,
 parameter integer C_PORTS_PER_TILE=32,parameter integer C_DST_COUNT=4096,
 parameter integer C_PORT_COUNT=32,
 parameter integer C_NUM_VOQS=C_NUM_GROUPS*C_TILES_PER_GROUP*C_PORTS_PER_TILE*4,
 parameter integer C_BANK_WIDTH=3,parameter integer C_RETURN_BANKS=32,
 parameter integer C_CREDIT_WIDTH=8,parameter integer C_RX_TOKEN_WIDTH=18,
 parameter integer C_COUNT_WIDTH=4,parameter integer C_PORTS=C_NUM_STATIONS*4,
 parameter integer C_RESOURCES=C_TILES_PER_GROUP*C_PORTS_PER_TILE*4,
 parameter integer C_LANES=C_TILES_PER_GROUP*C_BANKS_PER_TILE,
 parameter integer C_ACCOUNTS=(C_LANES+C_NUM_PLANES)*C_RESOURCES,
 parameter integer C_TOTAL_RESOURCES=C_NUM_GROUPS*C_RESOURCES,
 parameter integer C_TOTAL_ACCOUNTS=C_NUM_GROUPS*C_ACCOUNTS,
 parameter integer C_QUEUE_ENTRIES=C_NUM_GROUPS*C_TILES_PER_GROUP*C_NUM_VOQS,
 parameter integer C_STATUS_RESOURCES=(C_TOTAL_RESOURCES>=C_QUEUE_ENTRIES)?C_TOTAL_RESOURCES:C_QUEUE_ENTRIES,
 parameter integer C_RELEASE_TIMEOUT_CYCLES=16,parameter integer C_RELEASE_TIMER_WIDTH=16,
 parameter integer C_FABRIC_TIMEOUT_CYCLES=1024,
 parameter integer C_STATION_INDEX_WIDTH=(C_NUM_STATIONS<=2)?1:(C_NUM_STATIONS<=4)?2:(C_NUM_STATIONS<=8)?3:(C_NUM_STATIONS<=16)?4:(C_NUM_STATIONS<=32)?5:(C_NUM_STATIONS<=64)?6:(C_NUM_STATIONS<=128)?7:8,
 parameter integer C_PORT_INDEX_WIDTH=(C_PORT_COUNT<=2)?1:(C_PORT_COUNT<=4)?2:(C_PORT_COUNT<=8)?3:(C_PORT_COUNT<=16)?4:(C_PORT_COUNT<=32)?5:(C_PORT_COUNT<=64)?6:(C_PORT_COUNT<=128)?7:(C_PORT_COUNT<=256)?8:(C_PORT_COUNT<=512)?9:10,
 parameter integer C_PLANE_INDEX_WIDTH=(C_NUM_PLANES<=2)?1:(C_NUM_PLANES<=4)?2:(C_NUM_PLANES<=8)?3:(C_NUM_PLANES<=16)?4:5,
 parameter integer C_ROUTE_INDEX_WIDTH=(C_DST_COUNT<=32)?5:(C_DST_COUNT<=64)?6:(C_DST_COUNT<=128)?7:(C_DST_COUNT<=256)?8:(C_DST_COUNT<=512)?9:(C_DST_COUNT<=1024)?10:(C_DST_COUNT<=2048)?11:12,
 parameter integer C_RESOURCE_INDEX_WIDTH=(C_STATUS_RESOURCES<=2)?1:(C_STATUS_RESOURCES<=4)?2:(C_STATUS_RESOURCES<=8)?3:(C_STATUS_RESOURCES<=16)?4:(C_STATUS_RESOURCES<=32)?5:(C_STATUS_RESOURCES<=64)?6:(C_STATUS_RESOURCES<=128)?7:(C_STATUS_RESOURCES<=256)?8:(C_STATUS_RESOURCES<=512)?9:(C_STATUS_RESOURCES<=1024)?10:(C_STATUS_RESOURCES<=2048)?11:12,
 parameter integer C_ACCOUNT_INDEX_WIDTH=(C_TOTAL_ACCOUNTS<=2)?1:(C_TOTAL_ACCOUNTS<=4)?2:(C_TOTAL_ACCOUNTS<=8)?3:(C_TOTAL_ACCOUNTS<=16)?4:(C_TOTAL_ACCOUNTS<=32)?5:(C_TOTAL_ACCOUNTS<=64)?6:(C_TOTAL_ACCOUNTS<=128)?7:(C_TOTAL_ACCOUNTS<=256)?8:(C_TOTAL_ACCOUNTS<=512)?9:(C_TOTAL_ACCOUNTS<=1024)?10:(C_TOTAL_ACCOUNTS<=2048)?11:(C_TOTAL_ACCOUNTS<=4096)?12:(C_TOTAL_ACCOUNTS<=8192)?13:(C_TOTAL_ACCOUNTS<=16384)?14:(C_TOTAL_ACCOUNTS<=32768)?15:(C_TOTAL_ACCOUNTS<=65536)?16:(C_TOTAL_ACCOUNTS<=131072)?17:18,
 parameter integer C_BANDWIDTH_COUNTER_WIDTH=64
)(
 input wire i_clk,input wire i_rstn,input wire i_enable,
 input wire i_csr_req_valid,output wire o_csr_req_ready,input wire i_csr_req_write,
 input wire[15:0] i_csr_req_addr,input wire[31:0] i_csr_req_wdata,
 output wire o_csr_rsp_valid,input wire i_csr_rsp_ready,output wire[31:0] o_csr_rsp_rdata,
 output wire o_csr_rsp_error,output wire o_csr_rsp_unsupported,
 input wire[C_PORTS-1:0] i_lane_up,
 input wire[C_PORTS-1:0] i_link_rx_frame_valid,output wire[C_PORTS-1:0] o_link_rx_frame_ready,
 input wire[C_PORTS*512-1:0] i_link_rx_frame_data,input wire[C_PORTS-1:0] i_link_rx_frame_sop,
 input wire[C_PORTS-1:0] i_link_rx_frame_eop,input wire[C_PORTS-1:0] i_link_rx_fec_complete,input wire[C_PORTS-1:0] i_link_rx_crc_ok,
 output wire[C_PORTS-1:0] o_link_control_valid,input wire[C_PORTS-1:0] i_link_control_ready,
 output wire[C_PORTS-1:0] o_link_control_replay_request,output wire[C_PORTS*9-1:0] o_link_control_target,
 output wire[C_PORTS-1:0] o_crc_frame_valid,input wire[C_PORTS-1:0] i_crc_frame_ready,
 output wire[C_PORTS*512-1:0] o_crc_frame_data,output wire[C_PORTS-1:0] o_crc_frame_sop,output wire[C_PORTS-1:0] o_crc_frame_eop,
 output wire[C_PORTS*9-1:0] o_crc_frame_sequence,output wire[C_PORTS-1:0] o_crc_frame_replay,
 output wire[C_PORTS-1:0] o_crc_required,output wire[C_PORTS-1:0] o_physical_valid,output wire[C_PORTS*8-1:0] o_tx_resident_count,
 input wire[C_PORTS*4-1:0] i_upli_credit_connected,input wire[C_PORTS*4-1:0] i_upli_beats_connected,
 input wire[C_PORTS*4-1:0] i_upli_credit_valid,input wire[C_PORTS*4-1:0] i_upli_credit_pool,
 input wire[C_PORTS*8-1:0] i_upli_credit_vc,input wire[C_PORTS*8-1:0] i_upli_credit_num,input wire[C_PORTS*4-1:0] i_upli_credit_init_done,
 output wire[C_PORTS-1:0] o_upli_credit_candidate_ready,
 input wire[C_PORTS-1:0] i_tl_rx_start,input wire[C_PORTS-1:0] i_tl_rx_shared,input wire[C_PORTS*20*C_CREDIT_WIDTH-1:0] i_tl_rx_capacities,
 input wire[C_PORTS-1:0] i_release_path_enable,input wire[C_PORTS-1:0] i_egress_flush,
 output wire[C_NUM_STATIONS*2-1:0] o_station_active_mode,output wire[C_PORTS-1:0] o_port_active,
 output wire[C_PORTS*10-1:0] o_global_port_id,output wire[C_PORTS-1:0] o_rx_release_valid,
 output wire[C_PORTS*C_RX_TOKEN_WIDTH-1:0] o_rx_release_token,output wire[C_PORTS*80-1:0] o_rx_release_vector,
 output wire[C_PORTS-1:0] o_upli_mapping_unsupported,
 output wire o_route_commit_ready,output wire o_route_commit_rejected,output wire o_quiescent,
 output wire o_release_stall_active,output wire o_release_timeout_sticky,
 output wire[31:0] o_release_stall_cycles,output wire[31:0] o_release_timeout_count,
 output wire[C_PORTS-1:0] o_observe_ingress_committed_valid,
 output wire[C_PORTS-1:0] o_observe_ingress_committed_ready,
 output wire[C_PORTS-1:0] o_observe_egress_retired_valid,
 output wire[C_PORTS-1:0] o_observe_egress_retired_ready,
 output wire o_management_error,output wire o_config_error,output wire o_error,
 input wire i_bandwidth_window_start,input wire i_bandwidth_window_stop,
 output wire o_ingress_bandwidth_window_active,output wire o_ingress_bandwidth_window_done,
 output wire[C_BANDWIDTH_COUNTER_WIDTH-1:0] o_ingress_bandwidth_measurement_cycles,
 output wire[C_PORTS*C_BANDWIDTH_COUNTER_WIDTH-1:0] o_ingress_bandwidth_attempts,o_ingress_bandwidth_handshake_flits,
 output wire[C_PORTS*C_BANDWIDTH_COUNTER_WIDTH-1:0] o_ingress_bandwidth_payload_bytes,o_ingress_bandwidth_payload_bits,o_ingress_bandwidth_stall_cycles,
 output wire[C_PORTS*5-1:0] o_ingress_bandwidth_overflow_sticky,output wire o_ingress_bandwidth_window_overflow_sticky,
 output wire o_egress_bandwidth_window_active,output wire o_egress_bandwidth_window_done,
 output wire[C_BANDWIDTH_COUNTER_WIDTH-1:0] o_egress_bandwidth_measurement_cycles,
 output wire[C_PORTS*C_BANDWIDTH_COUNTER_WIDTH-1:0] o_egress_bandwidth_attempts,o_egress_bandwidth_handshake_flits,
 output wire[C_PORTS*C_BANDWIDTH_COUNTER_WIDTH-1:0] o_egress_bandwidth_payload_bytes,o_egress_bandwidth_payload_bits,o_egress_bandwidth_stall_cycles,
 output wire[C_PORTS*5-1:0] o_egress_bandwidth_overflow_sticky,output wire o_egress_bandwidth_window_overflow_sticky,
 output wire o_bandwidth_config_error,output wire o_bandwidth_error
);
 ualink_switch_full_ip_managed_top #(
  .C_NUM_STATIONS(C_NUM_STATIONS),
  .C_NUM_GROUPS(C_NUM_GROUPS),
  .C_TILES_PER_GROUP(C_TILES_PER_GROUP),
  .C_INGRESS_PER_TILE(C_INGRESS_PER_TILE),
  .C_BANKS_PER_TILE(C_BANKS_PER_TILE),
  .C_NUM_PLANES(C_NUM_PLANES),
  .C_PORTS_PER_TILE(C_PORTS_PER_TILE),
  .C_DST_COUNT(C_DST_COUNT),
  .C_PORT_COUNT(C_PORT_COUNT),
  .C_NUM_VOQS(C_NUM_VOQS),
  .C_BANK_WIDTH(C_BANK_WIDTH),
  .C_RETURN_BANKS(C_RETURN_BANKS),
  .C_CREDIT_WIDTH(C_CREDIT_WIDTH),
  .C_RX_TOKEN_WIDTH(C_RX_TOKEN_WIDTH),
  .C_COUNT_WIDTH(C_COUNT_WIDTH),
  .C_PORTS(C_PORTS),
  .C_RESOURCES(C_RESOURCES),
  .C_LANES(C_LANES),
  .C_ACCOUNTS(C_ACCOUNTS),
  .C_TOTAL_RESOURCES(C_TOTAL_RESOURCES),
  .C_TOTAL_ACCOUNTS(C_TOTAL_ACCOUNTS),
  .C_QUEUE_ENTRIES(C_QUEUE_ENTRIES),
  .C_STATUS_RESOURCES(C_STATUS_RESOURCES),
  .C_RELEASE_TIMEOUT_CYCLES(C_RELEASE_TIMEOUT_CYCLES),
  .C_RELEASE_TIMER_WIDTH(C_RELEASE_TIMER_WIDTH),
  .C_FABRIC_TIMEOUT_CYCLES(C_FABRIC_TIMEOUT_CYCLES),
  .C_STATION_INDEX_WIDTH(C_STATION_INDEX_WIDTH),
  .C_PORT_INDEX_WIDTH(C_PORT_INDEX_WIDTH),
  .C_PLANE_INDEX_WIDTH(C_PLANE_INDEX_WIDTH),
  .C_ROUTE_INDEX_WIDTH(C_ROUTE_INDEX_WIDTH),
  .C_RESOURCE_INDEX_WIDTH(C_RESOURCE_INDEX_WIDTH),
  .C_ACCOUNT_INDEX_WIDTH(C_ACCOUNT_INDEX_WIDTH))u_managed(
  .i_clk(i_clk),
  .i_rstn(i_rstn),
  .i_enable(i_enable),
  .i_csr_req_valid(i_csr_req_valid),
  .o_csr_req_ready(o_csr_req_ready),
  .i_csr_req_write(i_csr_req_write),
  .i_csr_req_addr(i_csr_req_addr),
  .i_csr_req_wdata(i_csr_req_wdata),
  .o_csr_rsp_valid(o_csr_rsp_valid),
  .i_csr_rsp_ready(i_csr_rsp_ready),
  .o_csr_rsp_rdata(o_csr_rsp_rdata),
  .o_csr_rsp_error(o_csr_rsp_error),
  .o_csr_rsp_unsupported(o_csr_rsp_unsupported),
  .i_lane_up(i_lane_up),
  .i_link_rx_frame_valid(i_link_rx_frame_valid),
  .o_link_rx_frame_ready(o_link_rx_frame_ready),
  .i_link_rx_frame_data(i_link_rx_frame_data),
  .i_link_rx_frame_sop(i_link_rx_frame_sop),
  .i_link_rx_frame_eop(i_link_rx_frame_eop),
  .i_link_rx_fec_complete(i_link_rx_fec_complete),
  .i_link_rx_crc_ok(i_link_rx_crc_ok),
  .o_link_control_valid(o_link_control_valid),
  .i_link_control_ready(i_link_control_ready),
  .o_link_control_replay_request(o_link_control_replay_request),
  .o_link_control_target(o_link_control_target),
  .o_crc_frame_valid(o_crc_frame_valid),
  .i_crc_frame_ready(i_crc_frame_ready),
  .o_crc_frame_data(o_crc_frame_data),
  .o_crc_frame_sop(o_crc_frame_sop),
  .o_crc_frame_eop(o_crc_frame_eop),
  .o_crc_frame_sequence(o_crc_frame_sequence),
  .o_crc_frame_replay(o_crc_frame_replay),
  .o_crc_required(o_crc_required),
  .o_physical_valid(o_physical_valid),
  .o_tx_resident_count(o_tx_resident_count),
  .i_upli_credit_connected(i_upli_credit_connected),
  .i_upli_beats_connected(i_upli_beats_connected),
  .i_upli_credit_valid(i_upli_credit_valid),
  .i_upli_credit_pool(i_upli_credit_pool),
  .i_upli_credit_vc(i_upli_credit_vc),
  .i_upli_credit_num(i_upli_credit_num),
  .i_upli_credit_init_done(i_upli_credit_init_done),
  .o_upli_credit_candidate_ready(o_upli_credit_candidate_ready),
  .i_tl_rx_start(i_tl_rx_start),
  .i_tl_rx_shared(i_tl_rx_shared),
  .i_tl_rx_capacities(i_tl_rx_capacities),
  .i_release_path_enable(i_release_path_enable),
  .i_egress_flush(i_egress_flush),
  .o_station_active_mode(o_station_active_mode),
  .o_port_active(o_port_active),
  .o_global_port_id(o_global_port_id),
  .o_rx_release_valid(o_rx_release_valid),
  .o_rx_release_token(o_rx_release_token),
  .o_rx_release_vector(o_rx_release_vector),
  .o_upli_mapping_unsupported(o_upli_mapping_unsupported),
  .o_route_commit_ready(o_route_commit_ready),
  .o_route_commit_rejected(o_route_commit_rejected),
  .o_quiescent(o_quiescent),
  .o_release_stall_active(o_release_stall_active),
  .o_release_timeout_sticky(o_release_timeout_sticky),
  .o_release_stall_cycles(o_release_stall_cycles),
  .o_release_timeout_count(o_release_timeout_count),
  .o_observe_ingress_committed_valid(o_observe_ingress_committed_valid),
  .o_observe_ingress_committed_ready(o_observe_ingress_committed_ready),
  .o_observe_egress_retired_valid(o_observe_egress_retired_valid),
  .o_observe_egress_retired_ready(o_observe_egress_retired_ready),
  .o_management_error(o_management_error),
  .o_config_error(o_config_error),
  .o_error(o_error));
 switch_managed_bandwidth_observer #(.C_PORTS(C_PORTS),.C_COUNTER_WIDTH(C_BANDWIDTH_COUNTER_WIDTH))u_bandwidth(
  .i_clk(i_clk),.i_rstn(i_rstn),.i_window_start(i_bandwidth_window_start),.i_window_stop(i_bandwidth_window_stop),
  .i_ingress_committed_valid(o_observe_ingress_committed_valid),.i_ingress_committed_ready(o_observe_ingress_committed_ready),
  .i_egress_retired_valid(o_observe_egress_retired_valid),.i_egress_retired_ready(o_observe_egress_retired_ready),
  .o_ingress_window_active(o_ingress_bandwidth_window_active),.o_ingress_window_done(o_ingress_bandwidth_window_done),
  .o_ingress_measurement_cycles(o_ingress_bandwidth_measurement_cycles),.o_ingress_attempts(o_ingress_bandwidth_attempts),
  .o_ingress_handshake_flits(o_ingress_bandwidth_handshake_flits),.o_ingress_payload_bytes(o_ingress_bandwidth_payload_bytes),
  .o_ingress_payload_bits(o_ingress_bandwidth_payload_bits),.o_ingress_stall_cycles(o_ingress_bandwidth_stall_cycles),
  .o_ingress_overflow_sticky(o_ingress_bandwidth_overflow_sticky),.o_ingress_window_overflow_sticky(o_ingress_bandwidth_window_overflow_sticky),
  .o_egress_window_active(o_egress_bandwidth_window_active),.o_egress_window_done(o_egress_bandwidth_window_done),
  .o_egress_measurement_cycles(o_egress_bandwidth_measurement_cycles),.o_egress_attempts(o_egress_bandwidth_attempts),
  .o_egress_handshake_flits(o_egress_bandwidth_handshake_flits),.o_egress_payload_bytes(o_egress_bandwidth_payload_bytes),
  .o_egress_payload_bits(o_egress_bandwidth_payload_bits),.o_egress_stall_cycles(o_egress_bandwidth_stall_cycles),
  .o_egress_overflow_sticky(o_egress_bandwidth_overflow_sticky),.o_egress_window_overflow_sticky(o_egress_bandwidth_window_overflow_sticky),
  .o_config_error(o_bandwidth_config_error),.o_error(o_bandwidth_error));
endmodule
`default_nettype wire
