`timescale 1ns/1ps
`default_nettype none
// Two-role native TX services; not a complete physical station or RX/RAS policy.
// Request/OrigData share one phase; Read and Write responses retain independent phases.
// Actual peer connection qualifications remain explicit; no acknowledgement is fabricated.
module upli_station_tx #(
    parameter integer C_NUM_PORTS = 1,
    parameter integer C_CREDIT_WIDTH = 4,
    parameter [C_CREDIT_WIDTH-1:0] C_DEFAULT_CAPACITY = 4,
    parameter [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] C_REQ_CAPACITIES = {C_NUM_PORTS*5{C_DEFAULT_CAPACITY}},
    parameter [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] C_DATA_CAPACITIES = {C_NUM_PORTS*5{C_DEFAULT_CAPACITY}},
    parameter [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] C_RD_CAPACITIES = {C_NUM_PORTS*5{C_DEFAULT_CAPACITY}},
    parameter [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] C_WR_CAPACITIES = {C_NUM_PORTS*5{C_DEFAULT_CAPACITY}},
    parameter integer C_INIT_COUNT_WIDTH = 4,
    parameter integer C_INIT_CYCLES = 2
) (
    input wire  i_clk,
    input wire  i_rstn,
    input wire  i_originator_credit_connected,
    input wire  i_originator_beats_connected,
    input wire  i_req_candidate_valid,
    input wire [1:0] i_req_candidate_port,
    input wire [1:0] i_req_candidate_vc,
    input wire  i_req_candidate_pool,
    input wire  i_req_candidate_has_data,
    input wire [1:0] i_req_candidate_num_beats,
    input wire [3:0] i_req_candidate_data_pools,
    input wire [183:0] i_req_candidate_request,
    input wire [2047:0] i_req_candidate_data,
    input wire [255:0] i_req_candidate_byte_enable,
    input wire [3:0] i_req_candidate_error,
    input wire [3:0] i_req_credit_valid,
    input wire [3:0] i_req_credit_pool,
    input wire [7:0] i_req_credit_vc,
    input wire [7:0] i_req_credit_num,
    input wire [3:0] i_req_credit_init_done,
    input wire [3:0] i_data_credit_valid,
    input wire [3:0] i_data_credit_pool,
    input wire [7:0] i_data_credit_vc,
    input wire [7:0] i_data_credit_num,
    input wire [3:0] i_data_credit_init_done,
    output wire  o_req_candidate_accepted,
    output wire  o_req_valid,
    output wire [1:0] o_req_port,
    output wire [1:0] o_req_vc,
    output wire  o_req_pool,
    output wire [183:0] o_req_payload,
    output wire  o_data_valid,
    output wire [1:0] o_data_port,
    output wire [1:0] o_data_vc,
    output wire  o_data_pool,
    output wire [1:0] o_data_offset,
    output wire  o_data_last,
    output wire [511:0] o_data_payload,
    output wire [63:0] o_data_byte_enable,
    output wire  o_data_error,
    output wire [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] o_req_balances,
    output wire [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] o_data_balances,
    output wire [3:0] o_req_init,
    output wire [3:0] o_data_init,
    output wire  o_req_credit_error,
    output wire  o_data_credit_error,
    output wire  o_req_data_credit_error_sticky,
    output wire [3:0] o_req_busy,
    output wire  o_req_tdm_known,
    output wire [1:0] o_req_tdm_port,
    output wire [1:0] o_req_asi,
    output wire [63:0] o_req_auth_tag,
    output wire [9:0] o_req_src,
    output wire [9:0] o_req_dst,
    output wire [10:0] o_req_tag,
    output wire [1:0] o_req_num_beats,
    output wire [56:0] o_req_address,
    output wire [5:0] o_req_command,
    output wire [5:0] o_req_length,
    output wire [7:0] o_req_attr,
    output wire [7:0] o_req_metadata,
    output wire  o_req_valid_parity,
    output wire  o_req_auth_tag_parity,
    output wire  o_req_address_parity,
    output wire  o_req_control_parity,
    output wire  o_data_valid_parity,
    output wire  o_data_byte_enable_parity,
    output wire  o_data_fields_parity,
    output wire [7:0] o_data_parity,
    input wire  i_completer_credit_connected,
    input wire  i_completer_beats_connected,
    input wire  i_rd_candidate_valid,
    input wire [1:0] i_rd_candidate_port,
    input wire [1:0] i_rd_candidate_vc,
    input wire [3:0] i_rd_candidate_pools,
    input wire [2475:0] i_rd_candidate_payload,
    input wire [3:0] i_rd_credit_valid,
    input wire [3:0] i_rd_credit_pool,
    input wire [7:0] i_rd_credit_vc,
    input wire [7:0] i_rd_credit_num,
    input wire [3:0] i_rd_credit_init_done,
    output wire  o_rd_candidate_accepted,
    output wire  o_rd_candidate_error,
    output wire  o_rd_valid,
    output wire [1:0] o_rd_port,
    output wire [63:0] o_rd_auth_tag,
    output wire [9:0] o_rd_src,
    output wire [9:0] o_rd_dst,
    output wire [10:0] o_rd_tag,
    output wire [1:0] o_rd_num_beats,
    output wire [511:0] o_rd_data,
    output wire [3:0] o_rd_status,
    output wire [1:0] o_rd_offset,
    output wire  o_rd_last,
    output wire  o_rd_data_error,
    output wire [1:0] o_rd_type_info,
    output wire [1:0] o_rd_vc,
    output wire  o_rd_pool,
    output wire  o_rd_valid_parity,
    output wire  o_rd_auth_tag_parity,
    output wire [7:0] o_rd_data_parity,
    output wire  o_rd_control_parity,
    output wire [618:0] o_rd_payload,
    output wire [3:0] o_rd_busy,
    output wire [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] o_rd_balances,
    output wire [3:0] o_rd_init_confirmed,
    output wire  o_rd_credit_error,
    output wire  o_rd_credit_error_sticky,
    output wire  o_rd_tdm_known,
    output wire [1:0] o_rd_tdm_port,
    input wire  i_wr_candidate_valid,
    input wire [1:0] i_wr_candidate_port,
    input wire [1:0] i_wr_candidate_vc,
    input wire  i_wr_candidate_pool,
    input wire [100:0] i_wr_candidate_payload,
    input wire [3:0] i_wr_credit_valid,
    input wire [3:0] i_wr_credit_pool,
    input wire [7:0] i_wr_credit_vc,
    input wire [7:0] i_wr_credit_num,
    input wire [3:0] i_wr_credit_init_done,
    output wire  o_wr_candidate_accepted,
    output wire  o_wr_valid,
    output wire [1:0] o_wr_type_info,
    output wire [10:0] o_wr_tag,
    output wire [3:0] o_wr_status,
    output wire [9:0] o_wr_src,
    output wire [9:0] o_wr_dst,
    output wire [1:0] o_wr_port,
    output wire [1:0] o_wr_vc,
    output wire  o_wr_pool,
    output wire [63:0] o_wr_auth_tag,
    output wire  o_wr_valid_parity,
    output wire  o_wr_auth_tag_parity,
    output wire  o_wr_control_parity,
    output wire [C_NUM_PORTS*5*C_CREDIT_WIDTH-1:0] o_wr_balances,
    output wire [3:0] o_wr_init_confirmed,
    output wire  o_wr_credit_error,
    output wire  o_wr_credit_error_sticky,
    output wire  o_wr_tdm_known,
    output wire [1:0] o_wr_tdm_port,
    input wire  i_req_credit_valid_parity,
    input wire  i_req_credit_parity,
    input wire  i_data_credit_valid_parity,
    input wire  i_data_credit_parity,
    input wire  i_rd_credit_valid_parity,
    input wire  i_rd_credit_parity,
    input wire  i_wr_credit_valid_parity,
    input wire  i_wr_credit_parity,
    output wire [3:0] o_credit_valid_parity_error,
    output wire [3:0] o_credit_control_parity_error,
    output wire [3:0] o_credit_parity_error,
    output wire [3:0] o_credit_integrity_ok
);
    upli_request_data_sender #(
        .C_NUM_PORTS(C_NUM_PORTS),
        .C_CREDIT_WIDTH(C_CREDIT_WIDTH),
        .C_DEFAULT_CAPACITY(C_DEFAULT_CAPACITY),
        .C_INIT_COUNT_WIDTH(C_INIT_COUNT_WIDTH),
        .C_INIT_CYCLES(C_INIT_CYCLES),
        .C_REQ_CAPACITIES(C_REQ_CAPACITIES),
        .C_DATA_CAPACITIES(C_DATA_CAPACITIES)
    ) u_req_sender (
        .i_clk(i_clk),
        .i_rstn(i_rstn),
        .i_credit_connected(i_originator_credit_connected),
        .i_beats_connected(i_originator_beats_connected),
        .i_candidate_valid(i_req_candidate_valid),
        .i_candidate_port(i_req_candidate_port),
        .i_candidate_vc(i_req_candidate_vc),
        .i_candidate_pool(i_req_candidate_pool),
        .i_candidate_has_data(i_req_candidate_has_data),
        .i_candidate_num_beats(i_req_candidate_num_beats),
        .i_candidate_data_pools(i_req_candidate_data_pools),
        .i_candidate_request(i_req_candidate_request),
        .i_candidate_data(i_req_candidate_data),
        .i_candidate_byte_enable(i_req_candidate_byte_enable),
        .i_candidate_error(i_req_candidate_error),
        .i_req_credit_valid(i_req_credit_valid),
        .i_req_credit_pool(i_req_credit_pool),
        .i_req_credit_vc(i_req_credit_vc),
        .i_req_credit_num(i_req_credit_num),
        .i_req_credit_init_done(i_req_credit_init_done),
        .i_data_credit_valid(i_data_credit_valid),
        .i_data_credit_pool(i_data_credit_pool),
        .i_data_credit_vc(i_data_credit_vc),
        .i_data_credit_num(i_data_credit_num),
        .i_data_credit_init_done(i_data_credit_init_done),
        .o_candidate_accepted(o_req_candidate_accepted),
        .o_req_valid(o_req_valid),
        .o_req_port(o_req_port),
        .o_req_vc(o_req_vc),
        .o_req_pool(o_req_pool),
        .o_req_payload(o_req_payload),
        .o_data_valid(o_data_valid),
        .o_data_port(o_data_port),
        .o_data_vc(o_data_vc),
        .o_data_pool(o_data_pool),
        .o_data_offset(o_data_offset),
        .o_data_last(o_data_last),
        .o_data_payload(o_data_payload),
        .o_data_byte_enable(o_data_byte_enable),
        .o_data_error(o_data_error),
        .o_req_balances(o_req_balances),
        .o_data_balances(o_data_balances),
        .o_req_init(o_req_init),
        .o_data_init(o_data_init),
        .o_req_credit_error(o_req_credit_error),
        .o_data_credit_error(o_data_credit_error),
        .o_credit_error_sticky(o_req_data_credit_error_sticky),
        .o_busy(o_req_busy),
        .o_tdm_known(o_req_tdm_known),
        .o_tdm_port(o_req_tdm_port),
        .o_req_asi(o_req_asi),
        .o_req_auth_tag(o_req_auth_tag),
        .o_req_src(o_req_src),
        .o_req_dst(o_req_dst),
        .o_req_tag(o_req_tag),
        .o_req_num_beats(o_req_num_beats),
        .o_req_address(o_req_address),
        .o_req_command(o_req_command),
        .o_req_length(o_req_length),
        .o_req_attr(o_req_attr),
        .o_req_metadata(o_req_metadata),
        .o_req_valid_parity(o_req_valid_parity),
        .o_req_auth_tag_parity(o_req_auth_tag_parity),
        .o_req_address_parity(o_req_address_parity),
        .o_req_control_parity(o_req_control_parity),
        .o_data_valid_parity(o_data_valid_parity),
        .o_data_byte_enable_parity(o_data_byte_enable_parity),
        .o_data_fields_parity(o_data_fields_parity),
        .o_data_parity(o_data_parity)
    );
    upli_read_response_sender #(
        .C_NUM_PORTS(C_NUM_PORTS),
        .C_CREDIT_WIDTH(C_CREDIT_WIDTH),
        .C_DEFAULT_CAPACITY(C_DEFAULT_CAPACITY),
        .C_INIT_COUNT_WIDTH(C_INIT_COUNT_WIDTH),
        .C_INIT_CYCLES(C_INIT_CYCLES),
        .C_CAPACITIES(C_RD_CAPACITIES)
    ) u_rd_sender (
        .i_clk(i_clk),
        .i_rstn(i_rstn),
        .i_credit_connected(i_completer_credit_connected),
        .i_beats_connected(i_completer_beats_connected),
        .i_candidate_valid(i_rd_candidate_valid),
        .i_candidate_port(i_rd_candidate_port),
        .i_candidate_vc(i_rd_candidate_vc),
        .i_candidate_pools(i_rd_candidate_pools),
        .i_candidate_payload(i_rd_candidate_payload),
        .i_credit_valid(i_rd_credit_valid),
        .i_credit_pool(i_rd_credit_pool),
        .i_credit_vc(i_rd_credit_vc),
        .i_credit_num(i_rd_credit_num),
        .i_credit_init_done(i_rd_credit_init_done),
        .o_candidate_accepted(o_rd_candidate_accepted),
        .o_candidate_error(o_rd_candidate_error),
        .o_valid(o_rd_valid),
        .o_port(o_rd_port),
        .o_auth_tag(o_rd_auth_tag),
        .o_src(o_rd_src),
        .o_dst(o_rd_dst),
        .o_tag(o_rd_tag),
        .o_num_beats(o_rd_num_beats),
        .o_data(o_rd_data),
        .o_status(o_rd_status),
        .o_offset(o_rd_offset),
        .o_last(o_rd_last),
        .o_data_error(o_rd_data_error),
        .o_type_info(o_rd_type_info),
        .o_vc(o_rd_vc),
        .o_pool(o_rd_pool),
        .o_valid_parity(o_rd_valid_parity),
        .o_auth_tag_parity(o_rd_auth_tag_parity),
        .o_data_parity(o_rd_data_parity),
        .o_control_parity(o_rd_control_parity),
        .o_payload(o_rd_payload),
        .o_busy(o_rd_busy),
        .o_balances(o_rd_balances),
        .o_init_confirmed(o_rd_init_confirmed),
        .o_credit_error(o_rd_credit_error),
        .o_credit_error_sticky(o_rd_credit_error_sticky),
        .o_tdm_known(o_rd_tdm_known),
        .o_tdm_port(o_rd_tdm_port)
    );
    upli_write_response_sender #(
        .C_NUM_PORTS(C_NUM_PORTS),
        .C_CREDIT_WIDTH(C_CREDIT_WIDTH),
        .C_DEFAULT_CAPACITY(C_DEFAULT_CAPACITY),
        .C_INIT_COUNT_WIDTH(C_INIT_COUNT_WIDTH),
        .C_INIT_CYCLES(C_INIT_CYCLES),
        .C_CAPACITIES(C_WR_CAPACITIES)
    ) u_wr_sender (
        .i_clk(i_clk),
        .i_rstn(i_rstn),
        .i_credit_connected(i_completer_credit_connected),
        .i_beats_connected(i_completer_beats_connected),
        .i_candidate_valid(i_wr_candidate_valid),
        .i_candidate_port(i_wr_candidate_port),
        .i_candidate_vc(i_wr_candidate_vc),
        .i_candidate_pool(i_wr_candidate_pool),
        .i_candidate_payload(i_wr_candidate_payload),
        .i_credit_valid(i_wr_credit_valid),
        .i_credit_pool(i_wr_credit_pool),
        .i_credit_vc(i_wr_credit_vc),
        .i_credit_num(i_wr_credit_num),
        .i_credit_init_done(i_wr_credit_init_done),
        .o_candidate_accepted(o_wr_candidate_accepted),
        .o_valid(o_wr_valid),
        .o_type_info(o_wr_type_info),
        .o_tag(o_wr_tag),
        .o_status(o_wr_status),
        .o_src(o_wr_src),
        .o_dst(o_wr_dst),
        .o_port(o_wr_port),
        .o_vc(o_wr_vc),
        .o_pool(o_wr_pool),
        .o_auth_tag(o_wr_auth_tag),
        .o_valid_parity(o_wr_valid_parity),
        .o_auth_tag_parity(o_wr_auth_tag_parity),
        .o_control_parity(o_wr_control_parity),
        .o_balances(o_wr_balances),
        .o_init_confirmed(o_wr_init_confirmed),
        .o_credit_error(o_wr_credit_error),
        .o_credit_error_sticky(o_wr_credit_error_sticky),
        .o_tdm_known(o_wr_tdm_known),
        .o_tdm_port(o_wr_tdm_port)
    );
    // Diagnostic-only guard: recovery and corrupted-credit policy belong to station RAS.
    upli_credit_guard u_req_credit_guard (
        .i_check_enable(i_rstn),
        .i_credit_valid(i_req_credit_valid),
        .i_credit_pool(i_req_credit_pool),
        .i_credit_vc(i_req_credit_vc),
        .i_credit_num(i_req_credit_num),
        .i_credit_valid_parity(i_req_credit_valid_parity),
        .i_credit_parity(i_req_credit_parity),
        .o_valid_error(o_credit_valid_parity_error[0]),
        .o_control_error(o_credit_control_parity_error[0]),
        .o_error(o_credit_parity_error[0]),
        .o_integrity_ok(o_credit_integrity_ok[0])
    );
    // Diagnostic-only guard: recovery and corrupted-credit policy belong to station RAS.
    upli_credit_guard u_data_credit_guard (
        .i_check_enable(i_rstn),
        .i_credit_valid(i_data_credit_valid),
        .i_credit_pool(i_data_credit_pool),
        .i_credit_vc(i_data_credit_vc),
        .i_credit_num(i_data_credit_num),
        .i_credit_valid_parity(i_data_credit_valid_parity),
        .i_credit_parity(i_data_credit_parity),
        .o_valid_error(o_credit_valid_parity_error[1]),
        .o_control_error(o_credit_control_parity_error[1]),
        .o_error(o_credit_parity_error[1]),
        .o_integrity_ok(o_credit_integrity_ok[1])
    );
    // Diagnostic-only guard: recovery and corrupted-credit policy belong to station RAS.
    upli_credit_guard u_rd_credit_guard (
        .i_check_enable(i_rstn),
        .i_credit_valid(i_rd_credit_valid),
        .i_credit_pool(i_rd_credit_pool),
        .i_credit_vc(i_rd_credit_vc),
        .i_credit_num(i_rd_credit_num),
        .i_credit_valid_parity(i_rd_credit_valid_parity),
        .i_credit_parity(i_rd_credit_parity),
        .o_valid_error(o_credit_valid_parity_error[2]),
        .o_control_error(o_credit_control_parity_error[2]),
        .o_error(o_credit_parity_error[2]),
        .o_integrity_ok(o_credit_integrity_ok[2])
    );
    // Diagnostic-only guard: recovery and corrupted-credit policy belong to station RAS.
    upli_credit_guard u_wr_credit_guard (
        .i_check_enable(i_rstn),
        .i_credit_valid(i_wr_credit_valid),
        .i_credit_pool(i_wr_credit_pool),
        .i_credit_vc(i_wr_credit_vc),
        .i_credit_num(i_wr_credit_num),
        .i_credit_valid_parity(i_wr_credit_valid_parity),
        .i_credit_parity(i_wr_credit_parity),
        .o_valid_error(o_credit_valid_parity_error[3]),
        .o_control_error(o_credit_control_parity_error[3]),
        .o_error(o_credit_parity_error[3]),
        .o_integrity_ok(o_credit_integrity_ok[3])
    );
endmodule
`default_nettype wire
